<?php

return [
    'push' => [
        'vapid_subject' => env('VAPID_SUBJECT', ''),
        'vapid_public_key' => env('VAPID_PUBLIC_KEY', ''),
        'vapid_private_key' => env('VAPID_PRIVATE_KEY', ''),
    ],
    'groups' => ['general', 'access', 'storage', 'security', 'sharing', 'maintenance', 'advanced'],
    'settings' => [
        'general.instance_name' => ['group' => 'general', 'api' => 'instanceName', 'type' => 'string', 'default' => 'Drive by NasLabs', 'rules' => ['required', 'string', 'max:120']],
        'general.brand_name' => ['group' => 'general', 'api' => 'brandName', 'type' => 'string', 'default' => 'NasLabs', 'rules' => ['required', 'string', 'max:120']],
        'general.app_url' => ['group' => 'general', 'api' => 'appUrl', 'type' => 'string', 'default' => config('app.frontend_url'), 'rules' => ['required', 'url', 'max:2048']],
        'general.description' => ['group' => 'general', 'api' => 'description', 'type' => 'string', 'default' => 'Private file storage', 'rules' => ['required', 'string', 'max:500']],
        'general.language' => ['group' => 'general', 'api' => 'language', 'type' => 'string', 'default' => 'en', 'rules' => ['required', 'in:en,id']],
        'general.timezone' => ['group' => 'general', 'api' => 'timezone', 'type' => 'string', 'default' => 'UTC', 'rules' => ['required', 'timezone']],
        'general.date_format' => ['group' => 'general', 'api' => 'dateFormat', 'type' => 'string', 'default' => 'Y-m-d', 'rules' => ['required', 'string', 'max:40']],
        'general.time_format' => ['group' => 'general', 'api' => 'timeFormat', 'type' => 'string', 'default' => 'H:i', 'rules' => ['required', 'string', 'max:40']],
        'access.public_registration' => ['group' => 'access', 'api' => 'publicRegistration', 'type' => 'boolean', 'default' => false, 'rules' => ['boolean']],
        'access.default_role' => ['group' => 'access', 'api' => 'defaultRole', 'type' => 'string', 'default' => 'user', 'rules' => ['required', 'in:user']],
        'storage.default_user_quota_bytes' => ['group' => 'storage', 'api' => 'defaultUserQuotaBytes', 'type' => 'integer', 'default' => (int) env('CLOUD_DEFAULT_USER_QUOTA_BYTES', 26_843_545_600), 'rules' => ['integer', 'min:1']],
        'storage.max_upload_size_bytes' => ['group' => 'storage', 'api' => 'maxUploadSizeBytes', 'type' => 'integer', 'default' => (int) env('CLOUD_MAX_UPLOAD_SIZE_BYTES', 524_288_000), 'rules' => ['integer', 'min:1', 'max:9223372036854775807']],
        'storage.trash_retention_days' => ['group' => 'storage', 'api' => 'trashRetentionDays', 'type' => 'integer', 'default' => 30, 'rules' => ['integer', 'min:1', 'max:3650']],
        'storage.trash_counts_toward_quota' => ['group' => 'storage', 'api' => 'trashCountsTowardQuota', 'type' => 'boolean', 'default' => true, 'rules' => ['boolean'], 'writable' => false],
        'storage.minimum_free_bytes' => ['group' => 'storage', 'api' => 'minimumFreeBytes', 'type' => 'integer', 'default' => 0, 'rules' => ['integer', 'min:0']],
        'storage.reserved_bytes' => ['group' => 'storage', 'api' => 'reservedBytes', 'type' => 'integer', 'default' => 0, 'rules' => ['integer', 'min:0']],
        'storage.blocked_extensions' => ['group' => 'storage', 'api' => 'blockedExtensions', 'type' => 'json', 'default' => config('cloud.blocked_extensions', []), 'rules' => ['array', 'max:100']],
        'storage.max_concurrent_uploads' => ['group' => 'storage', 'api' => 'maxConcurrentUploads', 'type' => 'integer', 'default' => 3, 'rules' => ['integer', 'min:1', 'max:20']],
        'storage.default_conflict_strategy' => ['group' => 'storage', 'api' => 'defaultConflictStrategy', 'type' => 'string', 'default' => 'ask', 'rules' => ['required', 'in:ask,keep_both,replace']],
        'storage.quota_warning_thresholds' => ['group' => 'storage', 'api' => 'quotaWarningThresholds', 'type' => 'json', 'default' => [80, 90, 100], 'rules' => ['array', 'max:10']],
        'security.password_min_length' => ['group' => 'security', 'api' => 'passwordMinLength', 'type' => 'integer', 'default' => 8, 'rules' => ['integer', 'min:8', 'max:128']],
        'security.password_require_uppercase' => ['group' => 'security', 'api' => 'passwordRequireUppercase', 'type' => 'boolean', 'default' => false, 'rules' => ['boolean']],
        'security.password_require_number' => ['group' => 'security', 'api' => 'passwordRequireNumber', 'type' => 'boolean', 'default' => false, 'rules' => ['boolean']],
        'security.password_require_special' => ['group' => 'security', 'api' => 'passwordRequireSpecial', 'type' => 'boolean', 'default' => false, 'rules' => ['boolean']],
        'sharing.internal_enabled' => ['group' => 'sharing', 'api' => 'internalEnabled', 'type' => 'boolean', 'default' => true, 'rules' => ['boolean']],
        'sharing.public_links_enabled' => ['group' => 'sharing', 'api' => 'publicLinksEnabled', 'type' => 'boolean', 'default' => true, 'rules' => ['boolean']],
        'maintenance.enabled' => ['group' => 'maintenance', 'api' => 'enabled', 'type' => 'boolean', 'default' => false, 'rules' => ['boolean']],
        'maintenance.message' => ['group' => 'maintenance', 'api' => 'message', 'type' => 'string', 'default' => 'Drive is temporarily unavailable for maintenance.', 'rules' => ['required', 'string', 'max:500']],
        'advanced.debug_ui' => ['group' => 'advanced', 'api' => 'debugUi', 'type' => 'boolean', 'default' => false, 'rules' => ['boolean'], 'writable' => false],
        'advanced.experimental_features' => ['group' => 'advanced', 'api' => 'experimentalFeatures', 'type' => 'json', 'default' => [], 'rules' => ['array', 'max:100'], 'writable' => false],
    ],
];
