'use client'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { Activity, Clock3, Files, HardDrive, Home, PanelLeftClose, PanelLeftOpen, Settings2, Share2, Star, Trash2, Cloud, X } from 'lucide-react'
import { formatBytes } from '@/lib/format'
import type { StorageSummary } from '@/types/cloud'

const primary = [{ href: '/home', label: 'Home', icon: Home }, { href: '/files', label: 'My Files', icon: Files }, { href: '/recent', label: 'Recent', icon: Clock3 }, { href: '/shared', label: 'Shared', icon: Share2 }, { href: '/starred', label: 'Starred', icon: Star }, { href: '/trash', label: 'Trash', icon: Trash2 }]
const secondary = [{ href: '/storage', label: 'Storage', icon: HardDrive }, { href: '/activity', label: 'Activity', icon: Activity }]
export function Sidebar({ storage, open, collapsed, onToggle, onClose }: { storage: StorageSummary; open: boolean; collapsed: boolean; onToggle: () => void; onClose: () => void }) {
  const pathname = usePathname(); const percent = Math.min(100, Math.round(storage.used / storage.total * 100)); const usageTone = percent > 95 ? 'critical' : percent > 80 ? 'warning' : 'normal'
  return <aside className={`sidebar ${open ? 'is-open' : ''} ${collapsed ? 'is-collapsed' : ''}`}><div className="brand"><div className="brand-mark" title="Drive by NasLabs"><Cloud size={17} /></div><div className="brand-copy"><div className="brand-name">Drive</div><div className="brand-byline">by NasLabs</div></div><button className="icon-button sidebar-toggle" onClick={onToggle} aria-label={collapsed ? 'Expand sidebar' : 'Collapse sidebar'} aria-expanded={!collapsed} title={collapsed ? 'Expand sidebar' : 'Collapse sidebar'}>{collapsed ? <PanelLeftOpen size={18} /> : <PanelLeftClose size={18} />}</button><button className="icon-button sidebar-close" onClick={onClose} aria-label="Close menu"><X size={18} /></button></div><nav className="nav-groups"><div className="nav-group">{primary.map(item => <NavItem key={item.href} {...item} collapsed={collapsed} active={pathname === item.href || (item.href === '/files' && pathname.startsWith('/files'))} />)}</div><div className="nav-divider" /><div className="nav-group">{secondary.map(item => <NavItem key={item.href} {...item} collapsed={collapsed} active={pathname === item.href} />)}</div><div className="nav-divider" /><div className="nav-group"><NavItem href="/settings" label="Settings" icon={Settings2} collapsed={collapsed} active={pathname.startsWith('/settings')} /></div></nav><div className="sidebar-bottom"><Link href="/storage" className={`storage-mini storage-${usageTone}`} aria-label="View storage usage"><div className="storage-mini-head"><span>Storage</span><span>{percent}%</span></div><div className="progress-track" role="progressbar" aria-label="Storage usage" aria-valuenow={percent} aria-valuemin={0} aria-valuemax={100}><span style={{ width: `${percent}%` }} /></div><span className="storage-caption">{formatBytes(storage.used)} of {formatBytes(storage.total)}</span></Link><Link href="/storage" className={`storage-mini-collapsed storage-${usageTone}`} aria-label={`Storage, ${formatBytes(storage.used)} of ${formatBytes(storage.total)}`} title={`Storage, ${formatBytes(storage.used)} of ${formatBytes(storage.total)}`}><HardDrive size={18} /><span style={{ height: `${Math.max(percent, 5)}%` }} /></Link></div></aside>
}
function NavItem({ href, label, icon: Icon, collapsed, active }: { href: string; label: string; icon: typeof Home; collapsed: boolean; active: boolean }) { return <Link href={href} className={`nav-item ${active ? 'active' : ''}`} title={collapsed ? label : undefined} aria-label={collapsed ? label : undefined}><Icon size={17} strokeWidth={1.8} /><span>{label}</span></Link> }
