'use client'
import Link from 'next/link'
import { Bell, Check, CloudUpload, Menu, Search, Settings, ShieldAlert, Share2, UserRound } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { ItemIcon } from '@/components/ui/Icon'
import { ThemeToggle } from '@/components/ui/ThemeToggle'
import { useAuthStore } from '@/stores/auth-store'
import { useRouter } from 'next/navigation'
import { formatRelative } from '@/lib/format'
import type { NotificationItem, NotificationType } from '@/types/notification'
import { notificationService } from '@/services/notification-service'
import { useCloudStore } from '@/stores/cloud-store'
export function Topbar({ onMenu }: { onMenu: () => void }) {
  const router = useRouter(); const auth = useAuthStore(); const currentUser = auth.currentUser; const cloud = useCloudStore(); const [query, setQuery] = useState(''); const [accountOpen, setAccountOpen] = useState(false); const [notificationsOpen, setNotificationsOpen] = useState(false); const [notifications, setNotifications] = useState<NotificationItem[]>([]); const [unreadCount, setUnreadCount] = useState(0); const [notificationError, setNotificationError] = useState(''); const notificationTriggerRef = useRef<HTMLButtonElement>(null); const accountTriggerRef = useRef<HTMLButtonElement>(null); const results = cloud.searchItems ?? []
  const refreshNotifications = async () => { try { const [list, count] = await Promise.all([notificationService.list(), notificationService.unreadCount()]); setNotifications(list); setUnreadCount(count); setNotificationError('') } catch (error) { setNotificationError(error instanceof Error ? error.message : 'Unable to load notifications.') } }
  const logout = async () => { try { await auth.logout() } catch { /* Local session state is cleared in the auth store even if the network request fails. */ } finally { setAccountOpen(false); router.replace('/login') } }
  useEffect(() => { const timer = window.setTimeout(() => { void cloud.search(query) }, query.trim() ? 250 : 0); return () => window.clearTimeout(timer) }, [cloud.search, query])
  useEffect(() => { const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') { if (accountOpen) accountTriggerRef.current?.focus(); else if (notificationsOpen) notificationTriggerRef.current?.focus(); setAccountOpen(false); setNotificationsOpen(false) } }; document.addEventListener('keydown', onKeyDown); return () => document.removeEventListener('keydown', onKeyDown) }, [accountOpen, notificationsOpen])
  const markAllRead = async () => { try { await notificationService.readAll(); await refreshNotifications() } catch (error) { setNotificationError(error instanceof Error ? error.message : 'Unable to update notifications.') } }
  const openNotification = async (notification: NotificationItem) => { try { await notificationService.read(notification.id); await refreshNotifications(); setNotificationsOpen(false); notificationTriggerRef.current?.focus(); if (notification.targetUrl) router.push(notification.targetUrl) } catch (error) { setNotificationError(error instanceof Error ? error.message : 'Unable to update notification.') } }
  const openAccount = () => { setNotificationsOpen(false); setAccountOpen(value => !value) }
  return <header className="topbar"><button className="menu-button icon-button" onClick={onMenu} aria-label="Open menu"><Menu size={20} /></button><div className="search-wrap"><Search size={17} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search files and folders" aria-label="Search files and folders" />{query && <div className="search-results">{results.length ? results.map(item => <Link key={item.id} href={item.kind === 'folder' ? `/files?folder=${item.id}` : '/files'} onClick={() => setQuery('')}><ItemIcon item={item} /><span>{item.name}</span><small>{item.path}</small></Link>) : <p>No files found</p>}</div>}</div><div className="topbar-actions"><div className="notification-wrap"><button ref={notificationTriggerRef} className="icon-button notification-trigger" onClick={() => { setAccountOpen(false); if (!notificationsOpen) void refreshNotifications(); setNotificationsOpen(value => !value) }} aria-label={`Notifications${unreadCount ? `, ${unreadCount} unread` : ''}`} aria-expanded={notificationsOpen} aria-haspopup="dialog"><Bell size={17} />{unreadCount > 0 && <span className="notification-dot" aria-label={`${unreadCount} unread notifications`} />}</button>{notificationsOpen && <NotificationPopover notifications={notifications} error={notificationError} onOpen={openNotification} onMarkAllRead={markAllRead} onViewActivity={() => { setNotificationsOpen(false); notificationTriggerRef.current?.focus(); router.push('/activity') }} />}</div><ThemeToggle /><div className="account-menu-wrap"><button ref={accountTriggerRef} className="avatar account-trigger" onClick={openAccount} aria-expanded={accountOpen} aria-haspopup="menu">{currentUser?.initials ?? "?"}</button>{accountOpen && <div className="account-menu account-menu-rich" role="menu"><div className="account-menu-profile"><div className="avatar large">{currentUser?.initials ?? "?"}</div><div><strong>{currentUser?.name ?? ""}</strong><span>{currentUser?.email ?? ""}</span><small>{currentUser?.role === 'admin' ? 'Administrator' : 'User'}</small></div></div><div className="account-menu-divider" /><Link href="/settings/profile" role="menuitem" onClick={() => setAccountOpen(false)}><UserRound size={15} />Profile</Link><Link href="/settings" role="menuitem" onClick={() => setAccountOpen(false)}><Settings size={15} />Settings</Link><Link href="/storage" role="menuitem" onClick={() => setAccountOpen(false)}><CloudUpload size={15} />My Storage</Link><div className="account-menu-divider" /><button onClick={logout} role="menuitem" className="sign-out-item"><ShieldAlert size={15} />Sign out</button></div>}</div></div></header>
}

function NotificationPopover({ notifications, error, onOpen, onMarkAllRead, onViewActivity }: { notifications: NotificationItem[]; error: string; onOpen: (notification: NotificationItem) => void; onMarkAllRead: () => void; onViewActivity: () => void }) {
  return <div className="notification-popover" role="dialog" aria-label="Notifications"><div className="notification-head"><strong>Notifications</strong><button className="text-action" onClick={onMarkAllRead}>Mark all as read</button></div>{error && <p className="form-hint error" role="alert">{error}</p>}<div className="notification-list">{notifications.map(notification => <button className={`notification-item ${notification.read ? '' : 'unread'}`} key={notification.id} onClick={() => onOpen(notification)}><NotificationIcon type={notification.type} /><span className="notification-copy"><strong>{notification.title}</strong><span>{notification.message}</span><small>{formatRelative(notification.createdAt)}</small></span>{!notification.read && <i aria-label="Unread" />}</button>)}</div><div className="notification-foot"><button className="text-action" onClick={onViewActivity}>View activity</button></div></div>
}

function NotificationIcon({ type }: { type: NotificationType }) { const Icon = type === 'upload' ? CloudUpload : type === 'sharing' ? Share2 : type === 'storage' ? ShieldAlert : Check; return <span className={`notification-icon ${type}`}><Icon size={14} /></span> }
