'use client'

import { use, useEffect, useState } from 'react'
import { Download, File, FileImage, FileText, Folder, Link2, X } from 'lucide-react'
import { FileViewer } from '@/components/files/FileViewer'
import type { CloudItem, PublicSharedItem } from '@/types/cloud'
import { formatBytes, formatDate } from '@/lib/format'
import { shareService } from '@/services/share-service'

export default function PublicSharePage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = use(params)
  const [resolution, setResolution] = useState<{ status: 'active'; ownerDisplayName: string; item: PublicSharedItem } | { status: 'unavailable' } | null>(null)
  const [current, setCurrent] = useState<PublicSharedItem | null>(null)
  const [breadcrumbs, setBreadcrumbs] = useState<PublicSharedItem[]>([])
  const [preview, setPreview] = useState<PublicSharedItem | null>(null)

  useEffect(() => { let active = true; void shareService.resolvePublicShare(token).then(async (data) => { if (!active) return; const root = { id: '', name: data.name, kind: data.type, fileType: data.mimeType?.startsWith('image/') ? 'image' : data.mimeType?.startsWith('video/') ? 'video' : data.mimeType?.startsWith('text/') ? 'document' : 'other', mimeType: data.mimeType ?? '', extension: data.name.includes('.') ? data.name.split('.').pop()!.toLowerCase() : '', size: data.sizeBytes ?? 0, modifiedAt: data.modifiedAt, children: [] } as PublicSharedItem; if (root.kind === 'folder') { const listing = await shareService.browsePublicShare(token); root.id = listing.sharedRoot.id; root.children = publicChildren(listing) } setResolution({ status: 'active', ownerDisplayName: data.ownerDisplayName, item: root }); setCurrent(root) }).catch(() => { if (active) setResolution({ status: 'unavailable' }) }); return () => { active = false } }, [token])

  if (!resolution) return <PublicState title="Loading shared item" description="Please wait while the link is checked." />
  if (resolution.status !== 'active') return <PublicState title="Link unavailable" description="This shared link is invalid or no longer available." />
  const activeItem = current ?? resolution.item
  const openFolder = (item: PublicSharedItem) => { setBreadcrumbs((currentTrail) => [...currentTrail, item]); void shareService.browsePublicShare(token, item.id).then(listing => setCurrent({ ...item, children: publicChildren(listing) })).catch(() => setCurrent({ ...item, children: [] })) }
  const goTo = (index: number) => { setBreadcrumbs((trail) => trail.slice(0, index)); setCurrent(index === 0 ? resolution.item : breadcrumbs[index - 1]) }
  return <div className="public-page"><PublicHeader /><main className="public-content"><div className="public-share-heading"><div><p className="public-kicker">Shared by {resolution.ownerDisplayName}</p><h1>{activeItem.name}</h1><p>{activeItem.kind === 'folder' ? `${activeItem.children.length} item${activeItem.children.length === 1 ? '' : 's'}` : `${activeItem.extension.toUpperCase() || 'FILE'} · ${formatBytes(activeItem.size)}`}</p></div><span className="public-viewer-label"><Link2 size={14} /> Viewer</span></div>{activeItem.kind === 'folder' ? <><nav className="public-breadcrumbs" aria-label="Shared folder breadcrumb"><button onClick={() => { setCurrent(resolution.item); setBreadcrumbs([]) }}>{resolution.item.name}</button>{breadcrumbs.slice(1).map((item, index) => <span key={`${item.name}-${index}`}><span aria-hidden="true">/</span><button onClick={() => goTo(index + 1)}>{item.name}</button></span>)}</nav><div className="public-folder-list">{activeItem.children.length ? activeItem.children.map((child) => <button key={child.id ?? child.name} className="public-folder-item" onClick={() => child.kind === 'folder' ? openFolder(child) : setPreview(child)}><span className="public-item-icon"><PublicItemIcon item={child} /></span><span><strong>{child.name}</strong><small>{child.kind === 'folder' ? `${child.children.length} item${child.children.length === 1 ? '' : 's'}` : `${child.extension.toUpperCase() || 'FILE'} · ${formatBytes(child.size)}`}</small></span></button>) : <p className="public-empty">This folder is empty.</p>}</div></> : <PublicFileCard item={activeItem} onPreview={() => setPreview(activeItem)} onDownload={() => downloadPublicItem(token, activeItem)} />}</main><PublicFooter />{preview && <PublicPreview token={token} item={preview} onClose={() => setPreview(null)} onDownload={() => downloadPublicItem(token, preview)} />}</div>
}

function PublicHeader() { return <header className="public-header"><div className="public-brand"><span aria-hidden="true"><Link2 size={15} /></span><div><strong>Cloud</strong><small>by NasLabs</small></div></div></header> }
function PublicFooter() { return <footer className="public-footer"><span>Cloud by NasLabs</span><span>© 2026 NasLabs</span></footer> }
function PublicState({ title, description }: { title: string; description: string }) { return <div className="public-page"><PublicHeader /><main className="public-state"><span className="public-state-icon"><Link2 size={20} /></span><h1>{title}</h1><p>{description}</p></main><PublicFooter /></div> }
function PublicFileCard({ item, onPreview, onDownload }: { item: PublicSharedItem; onPreview: () => void; onDownload: () => void }) { return <section className="public-file-card"><div className="public-file-preview"><PublicItemIcon item={item} /><span>{item.extension.toUpperCase() || 'FILE'}</span></div><div className="public-file-meta"><p>{item.name}</p><span>{item.mimeType} · {formatBytes(item.size)}</span><span>Modified {formatDate(item.modifiedAt)}</span></div><div className="public-actions"><button className="button secondary" onClick={onPreview}>Preview</button><button className="button primary" onClick={onDownload}><Download size={15} />Download</button></div></section> }
function PublicPreview({ token, item, onClose, onDownload }: { token: string; item: PublicSharedItem; onClose: () => void; onDownload: () => void }) { const adapter: CloudItem = { id: item.id ?? '', ownerId: 'public', name: item.name, kind: item.kind, fileType: item.fileType, mimeType: item.mimeType, extension: item.extension, size: item.size, parentId: null, path: '', createdAt: item.modifiedAt, updatedAt: item.modifiedAt, accessedAt: item.modifiedAt, starred: false, deletedAt: null, originalParentId: null, thumbnail: item.thumbnail }; return <div className="public-preview-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><div className="public-preview-dialog"><button className="public-preview-close" onClick={onClose} aria-label="Close preview"><X size={18} /></button><FileViewer item={adapter} publicMode publicToken={token} onClose={onClose} onDownload={onDownload} /></div></div> }
function PublicItemIcon({ item }: { item: PublicSharedItem }) { if (item.kind === 'folder') return <Folder size={22} />; if (item.fileType === 'image') return <FileImage size={22} />; if (item.fileType === 'document') return <FileText size={22} />; return <File size={22} /> }
function publicChildren(listing: Awaited<ReturnType<typeof shareService.browsePublicShare>>): PublicSharedItem[] { return [...listing.folders.map(folder => ({ id: folder.id, name: folder.name, kind: 'folder' as const, fileType: 'other' as const, mimeType: '', extension: '', size: 0, modifiedAt: folder.updatedAt, children: [] })), ...listing.files.map(file => ({ id: file.id, name: file.name, kind: 'file' as const, fileType: file.mimeType.startsWith('image/') ? 'image' as const : file.mimeType.startsWith('video/') ? 'video' as const : file.mimeType.startsWith('text/') ? 'document' as const : 'other' as const, mimeType: file.mimeType, extension: file.name.includes('.') ? file.name.split('.').pop()!.toLowerCase() : '', size: file.sizeBytes, modifiedAt: file.updatedAt, children: [] }))] }
function downloadPublicItem(token: string, item: PublicSharedItem) { void shareService.publicDownload(token, item.name, item.id || undefined).catch(() => undefined) }
