'use client'

import { useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { ChevronDown, Copy, Download, FileText, FolderPlus, Grid3X3, Move, Pencil, RotateCcw, Search, Share2, Star, Trash2, Upload, X } from 'lucide-react'
import { formatActivityMessage } from '@/lib/activity'
import { formatDate } from '@/lib/format'
import type { CloudActivity } from '@/types/cloud'
import type { useCloudStore } from '@/stores/cloud-store'

type Store = ReturnType<typeof useCloudStore>
const referenceTime = Date.now()
type ActionFilter = 'all' | 'upload' | 'change' | 'download' | 'trash' | 'restore' | 'starred'
type TypeFilter = 'all' | 'file' | 'folder'
type DateFilter = 'all' | 'today' | 'week' | 'month' | 'older'
const actionIcon: Record<CloudActivity['action'], typeof Upload> = { uploaded: Upload, opened: FileText, created: FolderPlus, renamed: Pencil, moved: Move, copied: Copy, downloaded: Download, deleted: Trash2, restored: RotateCcw, starred: Star, unstarred: Star, 'permanently-deleted': Trash2, 'emptied-trash': Trash2, shared: Share2, 'sharing-stopped': Share2 }
const actionGroup: Record<CloudActivity['action'], ActionFilter> = { uploaded: 'upload', opened: 'change', created: 'change', renamed: 'change', moved: 'change', copied: 'change', downloaded: 'download', deleted: 'trash', restored: 'restore', starred: 'starred', unstarred: 'starred', 'permanently-deleted': 'trash', 'emptied-trash': 'trash', shared: 'change', 'sharing-stopped': 'change' }

export function ActivityView({ store }: { store: Store }) {
  const router = useRouter(); const [query, setQuery] = useState(''); const [action, setAction] = useState<ActionFilter>('all'); const [type, setType] = useState<TypeFilter>('all'); const [date, setDate] = useState<DateFilter>('all'); const [selected, setSelected] = useState<CloudActivity | null>(null)
  const filtered = useMemo(() => store.activities.filter(activity => { const age = (referenceTime - new Date(activity.timestamp).getTime()) / 86400000; const matchesQuery = !query || `${activity.itemName} ${activity.action} ${activity.location} ${activity.targetLocation ?? ''}`.toLowerCase().includes(query.toLowerCase()); const matchesAction = action === 'all' || actionGroup[activity.action] === action; const matchesType = type === 'all' || activity.itemType === type; const matchesDate = date === 'all' || date === 'older' && age > 30 || date !== 'older' && age <= (date === 'today' ? 1 : date === 'week' ? 7 : 30); return matchesQuery && matchesAction && matchesType && matchesDate }).slice(0, 200), [action, date, query, store.activities, type])
  const groups = groupActivities(filtered); const clearFilters = () => { setQuery(''); setAction('all'); setType('all'); setDate('all') }; const showLocation = (activity: CloudActivity) => router.push(activity.location === 'Trash' ? '/trash' : activity.itemId ? `/files?folder=${activity.itemId}` : '/files')
  const overview = useMemo(() => { const today = store.activities.filter(item => (referenceTime - new Date(item.timestamp).getTime()) / 86400000 < 1).length; const week = store.activities.filter(item => (referenceTime - new Date(item.timestamp).getTime()) / 86400000 < 7).length; const actionCounts = store.activities.reduce<Record<string, number>>((counts, item) => ({ ...counts, [item.action]: (counts[item.action] ?? 0) + 1 }), {}); const mostCommonAction = Object.entries(actionCounts).sort((a, b) => b[1] - a[1])[0]?.[0] ?? 'No activity'; const locations = store.activities.reduce<Record<string, number>>((counts, item) => ({ ...counts, [item.location]: (counts[item.location] ?? 0) + 1 }), {}); const mostActiveLocation = Object.entries(locations).sort((a, b) => b[1] - a[1])[0]?.[0] ?? 'No location'; return { today, week, mostCommonAction, mostActiveLocation, last: store.activities[0] } }, [store.activities])
  return <div className="activity-workspace"><div className="activity-header"><div><h1>Activity</h1><p>Recent changes across your cloud.</p></div><button className="text-action" onClick={clearFilters}>Clear filters</button></div><div className="activity-toolbar"><div className="activity-search"><Search size={15} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search activity" aria-label="Search activity" /></div><FilterSelect label="Action" value={action} options={['all', 'upload', 'change', 'download', 'trash', 'restore', 'starred']} onChange={value => setAction(value as ActionFilter)} /><FilterSelect label="Type" value={type} options={['all', 'file', 'folder']} onChange={value => setType(value as TypeFilter)} /><FilterSelect label="Date" value={date} options={['all', 'today', 'week', 'month', 'older']} onChange={value => setDate(value as DateFilter)} /></div>{filtered.length === 0 ? <div className="activity-empty"><Grid3X3 size={22} /><h2>{query || action !== 'all' || type !== 'all' || date !== 'all' ? 'No activity matches your filters.' : 'No activity yet'}</h2><p>{query || action !== 'all' || type !== 'all' || date !== 'all' ? 'Try clearing a filter or using another term.' : 'Changes you make in Cloud will appear here.'}</p>{(query || action !== 'all' || type !== 'all' || date !== 'all') && <button className="text-action" onClick={clearFilters}>Clear filters</button>}</div> : <div className="activity-content-grid"><main className="activity-timeline-column"><div className="activity-result-note">{filtered.length} change{filtered.length === 1 ? '' : 's'} shown</div><div className="activity-groups">{groups.map(group => <section key={group.label}><h2 className="activity-group-title">{group.label}</h2><div className="activity-timeline">{group.items.map(activity => <ActivityItem key={activity.id} activity={activity} selected={selected?.id === activity.id} onClick={() => setSelected(activity)} onShowLocation={() => showLocation(activity)} />)}</div></section>)}</div></main><aside className="activity-context-rail">{selected ? <ActivityDetailsPanel activity={selected} onClose={() => setSelected(null)} onShowLocation={() => showLocation(selected)} /> : <ActivityOverview overview={overview} />}</aside></div>}{selected && <div className="activity-mobile-sheet"><ActivityDetailsPanel activity={selected} onClose={() => setSelected(null)} onShowLocation={() => { showLocation(selected); setSelected(null) }} /></div>}</div>
}

function groupActivities(items: CloudActivity[]) { const groups: Array<{ label: string; items: CloudActivity[] }> = []; items.forEach(activity => { const age = (referenceTime - new Date(activity.timestamp).getTime()) / 86400000; const label = age < 1 ? 'Today' : age < 2 ? 'Yesterday' : age < 7 ? 'Earlier this week' : age < 30 ? 'Earlier this month' : 'Older'; const group = groups.find(entry => entry.label === label); if (group) group.items.push(activity); else groups.push({ label, items: [activity] }) }); return groups }
function relativeTime(value: string) { const minutes = Math.max(1, Math.round((referenceTime - new Date(value).getTime()) / 60000)); return minutes < 60 ? `${minutes} minutes ago` : minutes < 1440 ? `${Math.round(minutes / 60)} hours ago` : `${Math.round(minutes / 1440)} days ago` }
function FilterSelect({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label className="filter-control activity-filter"><span>{label}</span><select value={value} onChange={event => onChange(event.target.value)} aria-label={label}>{options.map(option => <option key={option} value={option}>{option === 'all' ? 'All' : option[0].toUpperCase() + option.slice(1)}</option>)}</select><ChevronDown size={13} /></label> }
function ActivityItem({ activity, selected, onClick, onShowLocation }: { activity: CloudActivity; selected: boolean; onClick: () => void; onShowLocation: () => void }) { const Icon = actionIcon[activity.action]; const destructive = activity.action === 'deleted' || activity.action === 'permanently-deleted' || activity.action === 'emptied-trash'; return <article className={`activity-item ${selected ? 'selected' : ''}`} onClick={onClick}><div className={`activity-icon ${destructive ? 'destructive' : ''}`}><Icon size={16} /></div><div className="activity-item-copy"><button className="activity-message" onClick={onClick}>{formatActivityMessage(activity)}</button><button className="activity-location" onClick={event => { event.stopPropagation(); onShowLocation() }}>{activity.location}{activity.targetLocation ? ` → ${activity.targetLocation}` : ''}</button><span className="activity-time" title={formatDate(activity.timestamp)}>{relativeTime(activity.timestamp)}</span></div><button className="activity-more" onClick={onClick} aria-label="View activity details"><span>Details</span></button></article> }
function ActivityOverview({ overview }: { overview: { today: number; week: number; mostCommonAction: string; mostActiveLocation: string; last?: CloudActivity } }) { return <div className="activity-rail-panel"><div className="activity-rail-heading"><span className="eyebrow">Activity overview</span><h2>Workspace pulse</h2><p>A compact view of your recent changes.</p></div><div className="activity-key-values"><div><span>Today</span><strong>{overview.today} activit{overview.today === 1 ? 'y' : 'ies'}</strong></div><div><span>This week</span><strong>{overview.week} activit{overview.week === 1 ? 'y' : 'ies'}</strong></div><div><span>Most common action</span><strong>{overview.mostCommonAction}</strong></div><div><span>Most active location</span><strong>{overview.mostActiveLocation}</strong></div><div><span>Last activity</span><strong>{overview.last ? formatActivityMessage(overview.last) : 'No activity yet'}</strong></div></div></div> }
function ActivityDetailsPanel({ activity, onClose, onShowLocation }: { activity: CloudActivity; onClose: () => void; onShowLocation: () => void }) { return <div className="activity-rail-panel activity-detail-panel"><div className="activity-rail-heading"><div><span className="eyebrow">Selected activity</span><h2>Activity details</h2></div><button className="icon-button activity-detail-close" onClick={onClose} aria-label="Close activity details"><X size={16} /></button></div><div className="activity-key-values"><div><span>Action</span><strong>{formatActivityMessage(activity)}</strong></div><div><span>Item</span><strong>{activity.itemName}</strong></div><div><span>Type</span><strong>{activity.itemType === 'folder' ? 'Folder' : 'File'}</strong></div><div><span>Location</span><strong>{activity.location}</strong></div>{activity.targetLocation && <div><span>Destination</span><strong>{activity.targetLocation}</strong></div>}{activity.previousName && <div><span>Previous name</span><strong>{activity.previousName}</strong></div>}<div><span>Timestamp</span><strong>{formatDate(activity.timestamp)}</strong></div>{activity.metadata && <div><span>Details</span><strong>{activity.metadata}</strong></div>}</div><div className="activity-rail-actions"><button className="button primary" onClick={onShowLocation}>Show in folder</button><button className="button secondary" onClick={onClose}>Close</button></div></div> }
