'use client'

import { useEffect, useState } from 'react'
import { Check, Copy, Plus, Trash2, X } from 'lucide-react'
import { Modal } from '@/components/ui/Modal'
import { fileRequestsApi as shareService } from '@/features/file-requests/api/file-requests.api'
import type { CloudItem } from '@/types/cloud'

type RequestItem = { id: string; title: string; folderName?: string; enabled: boolean; expiresAt: string | null; url: string | null }
export function FileRequestDialog({ folders, onClose, onNotice }: { folders: CloudItem[]; onClose: () => void; onNotice?: (message: string) => void }) {
  const [requests, setRequests] = useState<RequestItem[]>([]); const [title, setTitle] = useState(''); const [folderId, setFolderId] = useState(folders[0]?.id ?? ''); const [expiration, setExpiration] = useState<'never' | '24h' | '7d' | '30d'>('never'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [copied, setCopied] = useState('')
  const refresh = async () => { try { setRequests(await shareService.getFileRequests()) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load file requests.') } }
  // Loading the owner-managed request list is an external synchronization.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void refresh() }, [])
  const create = async () => { if (!title.trim() || !folderId) return; setBusy(true); setError(''); try { const item = await shareService.createFileRequest({ title: title.trim(), folderId, expiration }); setRequests(current => [item, ...current]); setTitle(''); onNotice?.('File request created') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to create file request.') } finally { setBusy(false) } }
  const copy = async (item: RequestItem) => { if (!item.url) return; await navigator.clipboard.writeText(item.url); setCopied(item.id); window.setTimeout(() => setCopied(''), 1800) }
  return <Modal title="File requests" onClose={onClose}><div className="file-request-dialog">{error && <p className="form-hint error" role="alert">{error}</p>}<section><div className="share-section-heading"><strong>Create upload request</strong></div><label className="field-label">Request title<input className="text-input" value={title} onChange={event => setTitle(event.target.value)} placeholder="e.g. Send your documents" /></label><label className="field-label">Destination folder<select className="select-input" value={folderId} onChange={event => setFolderId(event.target.value)}>{folders.map(folder => <option key={folder.id} value={folder.id}>{folder.name}</option>)}</select></label><label className="field-label">Expiration<select className="select-input" value={expiration} onChange={event => setExpiration(event.target.value as typeof expiration)}><option value="never">Never</option><option value="24h">24 hours</option><option value="7d">7 days</option><option value="30d">30 days</option></select></label><button className="button primary" disabled={busy || !title.trim() || !folderId} onClick={() => void create()}><Plus size={14} />Create request</button></section><section><div className="share-section-heading"><strong>Active requests</strong><span>{requests.length}</span></div>{requests.length ? requests.map(item => <div className="file-request-row" key={item.id}><div><strong>{item.title}</strong><span>{item.folderName ?? 'Folder'} · {item.enabled ? 'Active' : 'Disabled'}</span></div>{item.enabled && <><button className="icon-button" onClick={() => void copy(item)} aria-label="Copy request link">{copied === item.id ? <Check size={15} /> : <Copy size={15} />}</button><button className="icon-button" onClick={() => void shareService.updateFileRequest(item.id, { enabled: false }).then(() => refresh())} aria-label="Disable request"><X size={15} /></button></>}<button className="icon-button danger-icon" onClick={() => void shareService.deleteFileRequest(item.id).then(() => refresh())} aria-label="Delete request"><Trash2 size={15} /></button></div>) : <p className="storage-muted">No file requests yet.</p>}</section></div></Modal>
}
