'use client'

import { useEffect, useState } from 'react'
import { usePathname, useRouter, useSearchParams } from 'next/navigation'
import Image from 'next/image'
import { Check, Database, FileUp, HardDrive, Info, LayoutDashboard, Palette, Settings2, ShieldCheck, UserRound, UsersRound } from 'lucide-react'
import { useUserStore } from '@/stores/user-store'
import type { CloudUser } from '@/types/user'
import { formatBytes, percentageOf } from '@/lib/format'
import { SystemSettingsSection } from '@/components/files/SystemSettingsView'
import { AccessDeniedState } from '@/components/system/SystemState'
import { UserManagement } from '@/components/files/UserManagement'
import { authApi } from '@/features/auth/api/auth.api'
import { useAuthStore } from '@/stores/auth-store'
import { NotificationPreferences } from '@/components/settings/NotificationPreferences'
import { SecuritySessions } from '@/components/settings/SecuritySessions'
import { AdminOverview } from '@/components/files/AdminOverview'
import { adminOverviewApi } from '@/features/admin/api/overview.api'
import type { AdminOverview as AdminOverviewData } from '@/features/admin/types/overview.types'
import { SettingsSegmented } from '@/components/settings/SettingsControls'

export type SettingsSection = 'profile' | 'security' | 'appearance' | 'files' | 'storage' | 'admin' | 'users' | 'storage-management' | 'system' | 'about'
type SettingsStore = ReturnType<typeof import('@/stores/cloud-store').useCloudStore>

export const settingsSections: Array<{ id: SettingsSection; label: string; group: string; admin?: boolean; icon: typeof UserRound }> = [
  { id: 'profile', label: 'Profil', group: 'Akun', icon: UserRound },
  { id: 'security', label: 'Keamanan', group: 'Akun', icon: ShieldCheck },
  { id: 'appearance', label: 'Tampilan', group: 'Preferensi', icon: Palette },
  { id: 'files', label: 'File & Unggahan', group: 'Preferensi', icon: FileUp },
  { id: 'storage', label: 'Penyimpanan Saya', group: 'Penyimpanan', icon: HardDrive },
  { id: 'admin', label: 'Ringkasan', group: 'Administrasi', admin: true, icon: LayoutDashboard },
  { id: 'users', label: 'Manajemen pengguna', group: 'Administrasi', admin: true, icon: UsersRound },
  { id: 'storage-management', label: 'Manajemen penyimpanan', group: 'Administrasi', admin: true, icon: Database },
  { id: 'system', label: 'Pengaturan sistem', group: 'Administrasi', admin: true, icon: Settings2 },
  { id: 'about', label: 'Tentang', group: 'Informasi', icon: Info },
]

export function SettingsNavigation({ selected, isAdmin, navigate }: { selected: SettingsSection; isAdmin: boolean; navigate: (section: SettingsSection) => void }) {
  return <nav className="settings-nav" aria-label="Bagian pengaturan">{['Akun', 'Preferensi', 'Penyimpanan', 'Administrasi', 'Informasi'].map(group => { const links = settingsSections.filter(section => section.group === group && (!section.admin || isAdmin)); return <div className="settings-nav-group" key={group}><span>{group}</span>{links.map(section => <button key={section.id} className={selected === section.id ? 'active' : ''} aria-current={selected === section.id ? 'page' : undefined} onClick={() => navigate(section.id)}><section.icon size={15} aria-hidden="true" /><span>{section.label}</span></button>)}</div> })}</nav>
}

function isSettingsSection(value: string | undefined): value is SettingsSection { return settingsSections.some(section => section.id === value) }

export function SettingsView({ store, sectionOverride, embedded = false }: { store: SettingsStore; sectionOverride?: SettingsSection; embedded?: boolean }) {
  const router = useRouter(); const pathname = usePathname(); const search = useSearchParams(); const userStore = useUserStore(); const auth = useAuthStore()
  const currentUser = userStore.currentUser
  const routeSection = pathname.split('/').pop(); const selected = sectionOverride ?? (isSettingsSection(routeSection) ? routeSection : undefined) ?? (search.get('section') as SettingsSection | null) ?? 'profile'
  const [notice, setNotice] = useState(''); const [profileName, setProfileName] = useState(currentUser?.name ?? ''); const profileEmail = currentUser?.email ?? ''; const [avatar, setAvatar] = useState(currentUser?.avatarUrl); const [density, setDensity] = useState(currentUser?.preferences.density ?? 'comfortable'); const [extensions, setExtensions] = useState(currentUser?.preferences.showFileExtensions ?? true); const [confirmDelete, setConfirmDelete] = useState(currentUser?.preferences.confirmPermanentDelete ?? true); const [sort, setSort] = useState(currentUser?.preferences.defaultSort ?? 'name'); const [conflict, setConflict] = useState(currentUser?.preferences.uploadConflict ?? 'ask')
  if (!currentUser) return <div className="settings-card" role="status">Loading account…</div>
  const navigate = (next: SettingsSection) => router.push(`/settings/${next}`)
  const isAdmin = currentUser.role === 'admin'
  const showNotice = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2600) }
  const saveProfile = async () => { try { await authApi.updateProfile(profileName); await auth.refreshUser(); showNotice('Profile changes saved') } catch (error) { showNotice(error instanceof Error ? error.message : 'Unable to save profile.') } }
  return <div className={`settings-workspace${embedded ? ' settings-workspace-embedded' : ''}`}><div className="settings-heading"><div><p className="section-kicker">Kontrol workspace</p><h1>Pengaturan</h1><p>Atur workspace Drive, akun, dan aturan akses Anda.</p></div><div className="settings-identity"><div className="avatar">{currentUser.initials}</div><span>{currentUser.role === 'admin' ? 'Administrator' : 'Anggota'}</span></div></div><div className="settings-layout">{!embedded && <SettingsNavigation selected={selected} isAdmin={isAdmin} navigate={navigate} />}<div className="settings-panel-area">{selected === 'profile' && <ProfileSection user={currentUser} name={profileName} email={profileEmail} avatar={avatar} setName={setProfileName} setAvatar={setAvatar} onSave={saveProfile} />} {selected === 'security' && <SecuritySection showNotice={showNotice} />} {selected === 'appearance' && <AppearanceSection store={store} />} {selected === 'files' && <FilesSection density={density} setDensity={setDensity} extensions={extensions} setExtensions={setExtensions} confirmDelete={confirmDelete} setConfirmDelete={setConfirmDelete} sort={sort} setSort={setSort} conflict={conflict} setConflict={setConflict} showNotice={showNotice} />} {selected === 'storage' && <MyStorageSection store={store} user={currentUser} />} {selected === 'admin' && (isAdmin ? <AdminOverview /> : <AccessDenied onBack={() => navigate('profile')} />)} {selected === 'users' && (isAdmin ? <UsersSection userStore={userStore} showNotice={showNotice} /> : <AccessDenied onBack={() => navigate('profile')} />)} {selected === 'storage-management' && (isAdmin ? <StorageManagementSection users={userStore.users} /> : <AccessDenied onBack={() => navigate('profile')} />)} {selected === 'system' && (isAdmin ? <SystemSettingsSection /> : <AccessDenied onBack={() => navigate('profile')} />)}</div></div>{notice && <div className="settings-toast" role="status"><Check size={15} />{notice}</div>}</div>
}

function SectionHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="settings-section-header"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{description}</p></div><div className="settings-header-actions">{action}</div></div> }
function ProfileSection({ user, name, email, avatar, setName, setAvatar, onSave }: { user: CloudUser; name: string; email: string; avatar?: string; setName: (value: string) => void; setAvatar: (value: string | undefined) => void; onSave: () => void }) { return <section className="settings-card"><SectionHeader eyebrow="Akun" title="Profil" description="Identitas workspace yang digunakan saat Anda berbagi dan berkolaborasi." /><div className="profile-editor"><div className="profile-avatar-wrap"><div className="avatar profile-avatar">{avatar ? <Image src={avatar} alt="" width={76} height={76} unoptimized /> : user.initials}</div><label className="button secondary">Unggah avatar<input type="file" accept="image/*" hidden disabled /></label>{avatar && <button className="text-action" onClick={() => setAvatar(undefined)}>Hapus</button>}</div><div className="settings-form-grid"><label>Nama tampilan<input className="text-input" value={name} onChange={event => setName(event.target.value)} /></label><label>Alamat email<input className="text-input" type="email" value={email} readOnly /></label><label>Peran<span className="readonly-field">{user.role === 'admin' ? 'Administrator' : 'Pengguna'} <small>Dikelola oleh administrator</small></span></label></div></div><div className="settings-actions"><button className="button primary" onClick={onSave}>Simpan perubahan</button></div></section> }
function SecuritySection({ showNotice }: { showNotice: (message: string) => void }) { const user = useUserStore().currentUser; const [busy, setBusy] = useState(false); const requestReset = async () => { if (!user) return; setBusy(true); try { await authApi.requestPasswordReset(user.email); showNotice('Jika akun tersedia, email reset kata sandi telah dikirim.') } catch (error) { showNotice(error instanceof Error ? error.message : 'Email reset kata sandi tidak dapat dikirim.') } finally { setBusy(false) } }; return <section className="settings-card"><SectionHeader eyebrow="Akun" title="Keamanan" description="Kelola akses masuk dan perangkat yang sedang menggunakan akun Anda." /><div className="security-settings-content"><div className="settings-form security-settings-block"><h3>Ubah kata sandi</h3><p>Formulir perubahan kata sandi belum tersedia. Minta email reset yang aman untuk melanjutkan.</p><button className="button primary" onClick={() => void requestReset()} disabled={busy || !user}>{busy ? 'Mengirim…' : 'Kirim email reset kata sandi'}</button></div><SecuritySessions onNotice={showNotice} /><NotificationPreferences onNotice={showNotice} /></div></section> }
function AppearanceSection({ store }: { store: SettingsStore }) { return <section className="settings-card"><SectionHeader eyebrow="Preferensi" title="Tampilan" description="Pilih mode visual dan tampilan kerja yang sesuai." /><div className="settings-options"><SettingRow label="Tema" description="Terang, gelap, atau mengikuti perangkat." control={<SettingsSegmented value={store.theme} onChange={value => store.setTheme(value)} ariaLabel="Pilih tema" options={[{ value: 'system', label: 'Sistem' }, { value: 'light', label: 'Terang' }, { value: 'dark', label: 'Gelap' }]} />} /><SettingRow label="Tampilan file default" description="Pilih layout yang digunakan di File Saya." control={<SettingsSegmented value={store.view} onChange={value => store.setView(value)} ariaLabel="Pilih tampilan file" options={[{ value: 'grid', label: 'Grid' }, { value: 'list', label: 'Daftar' }]} />} /></div></section> }
function FilesSection({ density, setDensity, extensions, setExtensions, confirmDelete, setConfirmDelete, sort, setSort, conflict, setConflict, showNotice }: { density: 'comfortable' | 'compact'; setDensity: (value: 'comfortable' | 'compact') => void; extensions: boolean; setExtensions: (value: boolean) => void; confirmDelete: boolean; setConfirmDelete: (value: boolean) => void; sort: 'name' | 'modified' | 'size'; setSort: (value: 'name' | 'modified' | 'size') => void; conflict: 'ask' | 'replace' | 'keep-both'; setConflict: (value: 'ask' | 'replace' | 'keep-both') => void; showNotice: (message: string) => void }) { return <section className="settings-card"><SectionHeader eyebrow="Preferensi" title="File & unggahan" description="Atur tampilan daftar file dan perilaku unggahan." /><div className="settings-options"><SettingRow label="Kepadatan" description="Atur jarak antarbaris pada tampilan daftar." control={<SettingsSegmented value={density} onChange={value => setDensity(value)} ariaLabel="Pilih kepadatan" options={[{ value: 'compact', label: 'Ringkas' }, { value: 'comfortable', label: 'Nyaman' }]} />} /><SettingRow label="Tampilkan ekstensi file" description="Pertahankan ekstensi pada nama file." control={<Toggle checked={extensions} onChange={() => setExtensions(!extensions)} />} /><SettingRow label="Urutan default" description="Pilih urutan awal daftar file." control={<select className="select-input" value={sort} onChange={event => setSort(event.target.value as 'name' | 'modified' | 'size')}><option value="modified">Terakhir diubah</option><option value="name">Nama</option><option value="size">Ukuran</option></select>} /><SettingRow label="Konflik unggahan" description="Tentukan tindakan saat nama file sudah ada." control={<select className="select-input" value={conflict} onChange={event => setConflict(event.target.value as 'ask' | 'replace' | 'keep-both')}><option value="ask">Tanyakan setiap kali</option><option value="replace">Ganti file lama</option><option value="keep-both">Simpan keduanya</option></select>} /><SettingRow label="Konfirmasi hapus permanen" description="Tambahkan konfirmasi sebelum tindakan yang tidak dapat dibatalkan." control={<Toggle checked={confirmDelete} onChange={() => setConfirmDelete(!confirmDelete)} />} /></div><div className="settings-actions"><button className="button primary" onClick={() => showNotice('Preferensi file disimpan untuk sesi ini')}>Simpan preferensi</button></div></section> }
function SettingRow({ label, description, control }: { label: string; description: string; control: React.ReactNode }) { return <div className="settings-option"><div><strong>{label}</strong><span>{description}</span></div>{control}</div> }
function Toggle({ checked, onChange }: { checked: boolean; onChange: () => void }) { return <button className={`toggle ${checked ? 'on' : ''}`} aria-pressed={checked} onClick={onChange}><span /></button> }
function MyStorageSection({ store, user }: { store: SettingsStore; user: CloudUser }) { const percent = percentageOf(store.storage.used, store.storage.total); return <section className="settings-card"><SectionHeader eyebrow="Penyimpanan" title="Penyimpanan saya" description="Kuota pribadi dan file yang sedang menggunakannya." /><div className="my-storage-total"><div><span>Terpakai</span><strong>{formatBytes(store.storage.used)}</strong><small>dari {formatBytes(user.quotaBytes)}</small></div><div className="storage-bar"><i style={{ width: `${percent}%` }} /></div><b>{percent.toFixed(1)}% terpakai</b></div><div className="settings-breakdown">{Object.entries(store.storage.categories).filter(([, value]) => value > 0).map(([label, value]) => <div key={label}><span>{label}</span><strong>{formatBytes(value)}</strong><i><em style={{ width: `${Math.max(percentageOf(value, store.storage.used), 2)}%` }} /></i></div>)}</div></section> }
function AccessDenied({ onBack }: { onBack: () => void }) { return <section className="settings-card access-denied"><AccessDeniedState adminOnly onBack={onBack} /></section> }
function UsersSection({ showNotice }: { showNotice: (message: string) => void; userStore?: ReturnType<typeof useUserStore> }) { return <UserManagement showNotice={showNotice} /> }
function StorageManagementSection({ users }: { users: CloudUser[] }) {
  const [summary, setSummary] = useState<AdminOverviewData['storage'] | null>(null)
  const [summaryError, setSummaryError] = useState('')
  const loadSummary = async () => {
    setSummaryError('')
    try { setSummary((await adminOverviewApi.get()).storage) } catch (error) { setSummaryError(error instanceof Error ? error.message : 'Unable to load storage totals.') }
  }
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void loadSummary() }, [])
  const total = summary?.quotaBytes ?? 0
  const used = summary?.usedBytes ?? 0
  return <section className="settings-card settings-admin-card"><SectionHeader eyebrow="Administrasi" title="Manajemen penyimpanan" description="Tinjau alokasi kuota dan penggunaan workspace." /><div className="storage-admin-overview"><div><span>Dialokasikan</span><strong>{summary ? formatBytes(total) : 'Memuat…'}</strong></div><div><span>Terpakai</span><strong>{summary ? formatBytes(used) : 'Memuat…'}</strong></div><div><span>Tersedia</span><strong>{summary ? formatBytes(summary.availableBytes) : 'Memuat…'}</strong></div></div>{summaryError && <div className="admin-overview-error storage-summary-error" role="alert"><span>{summaryError}</span><button type="button" className="button secondary" onClick={() => void loadSummary()}>Coba lagi</button></div>}<div className="admin-storage-list">{users.map(user => <div className="admin-storage-row" key={user.id}><div className="user-person"><div className="avatar">{user.initials}</div><div><strong>{user.name}</strong><span>{user.role === 'admin' ? 'Admin' : 'Pengguna'} · {user.status}</span></div></div><div className="admin-storage-meter"><div><i><em style={{ width: `${percentageOf(user.usedBytes, user.quotaBytes)}%` }} /></i><span>{formatBytes(user.usedBytes)} dari {formatBytes(user.quotaBytes)}</span></div><button className="button secondary">Kelola</button></div></div>)}</div></section>
}
