'use client'

import { useState } from 'react'
import { usePathname, useRouter, useSearchParams } from 'next/navigation'
import Image from 'next/image'
import { Check, Database, FileUp, HardDrive, Info, Palette, Settings2, ShieldCheck, UserRound, UsersRound } from 'lucide-react'
import { useUserStore } from '@/stores/user-store'
import type { CloudUser } from '@/types/user'
import { formatBytes, percentageOf } from '@/lib/format'
import { SystemSettingsSection } from '@/components/files/SystemSettingsView'
import { AccessDeniedState } from '@/components/system/SystemState'
import { UserManagement } from '@/components/files/UserManagement'
import { authApi } from '@/features/auth/api/auth.api'
import { useAuthStore } from '@/stores/auth-store'
import { NotificationPreferences } from '@/components/settings/NotificationPreferences'
import { SecuritySessions } from '@/components/settings/SecuritySessions'

export type SettingsSection = 'profile' | 'security' | 'appearance' | 'files' | 'storage' | 'users' | 'storage-management' | 'system' | 'about'
type SettingsStore = ReturnType<typeof import('@/stores/cloud-store').useCloudStore>

export const settingsSections: Array<{ id: SettingsSection; label: string; group: string; admin?: boolean; icon: typeof UserRound }> = [
  { id: 'profile', label: 'Profile', group: 'Account', icon: UserRound },
  { id: 'security', label: 'Security', group: 'Account', icon: ShieldCheck },
  { id: 'appearance', label: 'Appearance', group: 'Preferences', icon: Palette },
  { id: 'files', label: 'Files & Uploads', group: 'Preferences', icon: FileUp },
  { id: 'storage', label: 'My Storage', group: 'Storage', icon: HardDrive },
  { id: 'users', label: 'User Management', group: 'Administration', admin: true, icon: UsersRound },
  { id: 'storage-management', label: 'Storage Management', group: 'Administration', admin: true, icon: Database },
  { id: 'system', label: 'System Settings', group: 'Administration', admin: true, icon: Settings2 },
  { id: 'about', label: 'About', group: 'Information', icon: Info },
]

export function SettingsNavigation({ selected, isAdmin, navigate }: { selected: SettingsSection; isAdmin: boolean; navigate: (section: SettingsSection) => void }) {
  return <nav className="settings-nav" aria-label="Settings sections">{['Account', 'Preferences', 'Storage', 'Administration', 'Information'].map(group => { const links = settingsSections.filter(section => section.group === group && (!section.admin || isAdmin)); return <div className="settings-nav-group" key={group}><span>{group}</span>{links.map(section => <button key={section.id} className={selected === section.id ? 'active' : ''} aria-current={selected === section.id ? 'page' : undefined} onClick={() => navigate(section.id)}><section.icon size={15} aria-hidden="true" /><span>{section.label}</span></button>)}</div> })}</nav>
}

function isSettingsSection(value: string | undefined): value is SettingsSection { return settingsSections.some(section => section.id === value) }

export function SettingsView({ store, sectionOverride, embedded = false }: { store: SettingsStore; sectionOverride?: SettingsSection; embedded?: boolean }) {
  const router = useRouter(); const pathname = usePathname(); const search = useSearchParams(); const userStore = useUserStore(); const auth = useAuthStore()
  const currentUser = userStore.currentUser
  const routeSection = pathname.split('/').pop(); const selected = sectionOverride ?? (isSettingsSection(routeSection) ? routeSection : undefined) ?? (search.get('section') as SettingsSection | null) ?? 'profile'
  const [notice, setNotice] = useState(''); const [profileName, setProfileName] = useState(currentUser?.name ?? ''); const profileEmail = currentUser?.email ?? ''; const [avatar, setAvatar] = useState(currentUser?.avatarUrl); const [density, setDensity] = useState(currentUser?.preferences.density ?? 'comfortable'); const [extensions, setExtensions] = useState(currentUser?.preferences.showFileExtensions ?? true); const [confirmDelete, setConfirmDelete] = useState(currentUser?.preferences.confirmPermanentDelete ?? true); const [sort, setSort] = useState(currentUser?.preferences.defaultSort ?? 'name'); const [conflict, setConflict] = useState(currentUser?.preferences.uploadConflict ?? 'ask')
  if (!currentUser) return <div className="settings-card" role="status">Loading account…</div>
  const navigate = (next: SettingsSection) => router.push(`/settings/${next}`)
  const isAdmin = currentUser.role === 'admin'
  const showNotice = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2600) }
  const saveProfile = async () => { try { await authApi.updateProfile(profileName); await auth.refreshUser(); showNotice('Profile changes saved') } catch (error) { showNotice(error instanceof Error ? error.message : 'Unable to save profile.') } }
  return <div className={`settings-workspace${embedded ? ' settings-workspace-embedded' : ''}`}><div className="settings-heading"><div><p className="section-kicker">Workspace controls</p><h1>Settings</h1><p>Shape your Drive workspace, account, and access rules.</p></div><div className="settings-identity"><div className="avatar">{currentUser.initials}</div><span>{currentUser.role === 'admin' ? 'Administrator' : 'Member'}</span></div></div><div className="settings-layout">{!embedded && <SettingsNavigation selected={selected} isAdmin={isAdmin} navigate={navigate} />}<div className="settings-panel-area">{selected === 'profile' && <ProfileSection user={currentUser} name={profileName} email={profileEmail} avatar={avatar} setName={setProfileName} setAvatar={setAvatar} onSave={saveProfile} />} {selected === 'security' && <SecuritySection showNotice={showNotice} />} {selected === 'appearance' && <AppearanceSection store={store} />} {selected === 'files' && <FilesSection density={density} setDensity={setDensity} extensions={extensions} setExtensions={setExtensions} confirmDelete={confirmDelete} setConfirmDelete={setConfirmDelete} sort={sort} setSort={setSort} conflict={conflict} setConflict={setConflict} showNotice={showNotice} />} {selected === 'storage' && <MyStorageSection store={store} user={currentUser} />} {selected === 'users' && (isAdmin ? <UsersSection userStore={userStore} showNotice={showNotice} /> : <AccessDenied onBack={() => navigate('profile')} />)} {selected === 'storage-management' && (isAdmin ? <StorageManagementSection users={userStore.users} /> : <AccessDenied onBack={() => navigate('profile')} />)} {selected === 'system' && (isAdmin ? <SystemSettingsSection /> : <AccessDenied onBack={() => navigate('profile')} />)}</div></div>{notice && <div className="settings-toast" role="status"><Check size={15} />{notice}</div>}</div>
}

function SectionHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { const userStore = useUserStore(); return <div className="settings-section-header"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{description}</p></div><div className="settings-header-actions">{process.env.NODE_ENV === 'development' && <label className="dev-switcher">Dev account<select className="select-input" value={userStore.currentUserId} onChange={event => void event}>{userStore.users.map(user => <option key={user.id} value={user.id}>{user.name} · {user.role}</option>)}</select></label>}{action}</div></div> }
function ProfileSection({ user, name, email, avatar, setName, setAvatar, onSave }: { user: CloudUser; name: string; email: string; avatar?: string; setName: (value: string) => void; setAvatar: (value: string | undefined) => void; onSave: () => void }) { return <section className="settings-card"><SectionHeader eyebrow="Account" title="Profile" description="The identity your workspace uses when you share and collaborate." /><div className="profile-editor"><div className="profile-avatar-wrap"><div className="avatar profile-avatar">{avatar ? <Image src={avatar} alt="" width={76} height={76} unoptimized /> : user.initials}</div><label className="button secondary">Upload avatar<input type="file" accept="image/*" hidden disabled /></label>{avatar && <button className="text-action" onClick={() => setAvatar(undefined)}>Remove</button>}</div><div className="settings-form-grid"><label>Display name<input className="text-input" value={name} onChange={event => setName(event.target.value)} /></label><label>Email address<input className="text-input" type="email" value={email} readOnly /></label><label>Role<span className="readonly-field">{user.role === 'admin' ? 'Administrator' : 'User'} <small>Managed by an administrator</small></span></label></div></div><div className="settings-actions"><button className="button primary" onClick={onSave}>Save changes</button></div></section> }
function SecuritySection({ showNotice }: { showNotice: (message: string) => void }) { const user = useUserStore().currentUser; const [busy, setBusy] = useState(false); const requestReset = async () => { if (!user) return; setBusy(true); try { await authApi.requestPasswordReset(user.email); showNotice('If the account exists, a password reset link has been sent.') } catch (error) { showNotice(error instanceof Error ? error.message : 'Unable to request a password reset.') } finally { setBusy(false) } }; return <section className="settings-card"><SectionHeader eyebrow="Account" title="Security" description="Keep your sign-in details and active sessions under control." /><div className="security-grid"><div className="settings-form"><h3>Change password</h3><p>A password change form is not supported by the backend yet. You can request a secure reset email instead.</p><button className="button primary" onClick={() => void requestReset()} disabled={busy || !user}>{busy ? 'Sending…' : 'Send password reset email'}</button></div><SecuritySessions onNotice={showNotice} /></div><NotificationPreferences onNotice={showNotice} /></section> }
function AppearanceSection({ store }: { store: SettingsStore }) { return <section className="settings-card"><SectionHeader eyebrow="Preferences" title="Appearance" description="Choose the visual mode and working view that feel right." /><div className="settings-options"><SettingRow label="Theme" description="Light, dark, or follow your device." control={<select className="select-input" value={store.theme} onChange={event => store.setTheme(event.target.value as 'light' | 'dark' | 'system')}><option value="light">Light</option><option value="dark">Dark</option><option value="system">System</option></select>} /><SettingRow label="Default file view" description="Pick the layout used in My Files." control={<select className="select-input" value={store.view} onChange={event => store.setView(event.target.value as 'list' | 'grid')}><option value="grid">Grid</option><option value="list">List</option></select>} /></div></section> }
function FilesSection({ density, setDensity, extensions, setExtensions, confirmDelete, setConfirmDelete, sort, setSort, conflict, setConflict, showNotice }: { density: 'comfortable' | 'compact'; setDensity: (value: 'comfortable' | 'compact') => void; extensions: boolean; setExtensions: (value: boolean) => void; confirmDelete: boolean; setConfirmDelete: (value: boolean) => void; sort: 'name' | 'modified' | 'size'; setSort: (value: 'name' | 'modified' | 'size') => void; conflict: 'ask' | 'replace' | 'keep-both'; setConflict: (value: 'ask' | 'replace' | 'keep-both') => void; showNotice: (message: string) => void }) { return <section className="settings-card"><SectionHeader eyebrow="Preferences" title="Files & uploads" description="Tune how file lists look and how uploads behave." /><div className="settings-options"><SettingRow label="Density" description="Adjust row spacing in list views." control={<select className="select-input" value={density} onChange={event => setDensity(event.target.value as 'comfortable' | 'compact')}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select>} /><SettingRow label="Show file extensions" description="Keep extensions visible in file names." control={<Toggle checked={extensions} onChange={() => setExtensions(!extensions)} />} /><SettingRow label="Default sort" description="Choose the first ordering for file lists." control={<select className="select-input" value={sort} onChange={event => setSort(event.target.value as 'name' | 'modified' | 'size')}><option value="modified">Last modified</option><option value="name">Name</option><option value="size">Size</option></select>} /><SettingRow label="Upload conflicts" description="What happens when a name already exists." control={<select className="select-input" value={conflict} onChange={event => setConflict(event.target.value as 'ask' | 'replace' | 'keep-both')}><option value="ask">Ask every time</option><option value="replace">Replace existing</option><option value="keep-both">Keep both</option></select>} /><SettingRow label="Confirm permanent delete" description="Add a confirmation before an irreversible action." control={<Toggle checked={confirmDelete} onChange={() => setConfirmDelete(!confirmDelete)} />} /></div><div className="settings-actions"><button className="button primary" onClick={() => showNotice('File preferences updated for this session only')}>Save preferences</button></div></section> }
function SettingRow({ label, description, control }: { label: string; description: string; control: React.ReactNode }) { return <div className="settings-option"><div><strong>{label}</strong><span>{description}</span></div>{control}</div> }
function Toggle({ checked, onChange }: { checked: boolean; onChange: () => void }) { return <button className={`toggle ${checked ? 'on' : ''}`} aria-pressed={checked} onClick={onChange}><span /></button> }
function MyStorageSection({ store, user }: { store: SettingsStore; user: CloudUser }) { const percent = percentageOf(store.storage.used, store.storage.total); return <section className="settings-card"><SectionHeader eyebrow="Storage" title="My storage" description="Your personal quota and the files currently using it." /><div className="my-storage-total"><div><span>Used</span><strong>{formatBytes(store.storage.used)}</strong><small>of {formatBytes(user.quotaBytes)}</small></div><div className="storage-bar"><i style={{ width: `${percent}%` }} /></div><b>{percent.toFixed(1)}% used</b></div><div className="settings-breakdown">{Object.entries(store.storage.categories).filter(([, value]) => value > 0).map(([label, value]) => <div key={label}><span>{label}</span><strong>{formatBytes(value)}</strong><i><em style={{ width: `${Math.max(percentageOf(value, store.storage.used), 2)}%` }} /></i></div>)}</div></section> }
function AccessDenied({ onBack }: { onBack: () => void }) { return <section className="settings-card access-denied"><AccessDeniedState adminOnly onBack={onBack} /></section> }
function UsersSection({ showNotice }: { showNotice: (message: string) => void; userStore?: ReturnType<typeof useUserStore> }) { return <UserManagement showNotice={showNotice} /> }
function StorageManagementSection({ users }: { users: CloudUser[] }) { const total = users.reduce((sum, user) => sum + user.quotaBytes, 0); const used = users.reduce((sum, user) => sum + user.usedBytes, 0); return <section className="settings-card settings-admin-card"><SectionHeader eyebrow="Administration" title="Storage management" description="Review quota allocation and usage across the workspace." /><div className="storage-admin-overview"><div><span>Allocated</span><strong>{formatBytes(total)}</strong></div><div><span>Used</span><strong>{formatBytes(used)}</strong></div><div><span>Available</span><strong>{formatBytes(total - used)}</strong></div></div><div className="admin-storage-list">{users.map(user => <div className="admin-storage-row" key={user.id}><div className="user-person"><div className="avatar">{user.initials}</div><div><strong>{user.name}</strong><span>{user.role === 'admin' ? 'Admin' : 'User'} · {user.status}</span></div></div><div className="admin-storage-meter"><div><i><em style={{ width: `${percentageOf(user.usedBytes, user.quotaBytes)}%` }} /></i><span>{formatBytes(user.usedBytes)} of {formatBytes(user.quotaBytes)}</span></div><button className="button secondary">Manage</button></div></div>)}</div></section> }
