'use client'

import { useEffect, useState } from 'react'
import { Check, ShieldCheck } from 'lucide-react'
import { systemSettingsApi } from '@/features/admin/api/system-settings.api'

type SystemTab = 'general' | 'access' | 'storage' | 'security' | 'maintenance' | 'advanced'
type ToggleKey = 'publicRegistration' | 'allowLogin' | 'maintenanceLogin' | 'rememberMe' | 'logoutDisabled' | 'allowFolderUpload' | 'allowDragDrop' | 'trashEnabled' | 'countTrash' | 'allowRestore' | 'strongPassword' | 'revokeSessions' | 'maintenanceEnabled' | 'debugUi' | 'experimentalFeatures'
type SystemSettings = Record<ToggleKey, boolean> & { maintenanceMessage: string; instanceName: string; brandName: string; instanceUrl: string; description: string; language: string; timezone: string; dateFormat: string; timeFormat: string; userCreation: string; maxAttempts: string; sessionLifetime: string; defaultRole: string; quota: string; defaultTheme: string; defaultView: string; conflict: string; capacity: string; reserved: string; warning: string; maxFileSize: string; trashRetention: string; concurrentUploads: string; allowedTypes: string; blockedExtensions: string; minPassword: string }

const initialSettings: SystemSettings = { instanceName: '', brandName: '', instanceUrl: '', description: '', language: '', timezone: '', dateFormat: '', timeFormat: '', userCreation: '', maxAttempts: '', sessionLifetime: '', defaultRole: 'User', quota: '0 GB', defaultTheme: '', defaultView: '', conflict: '', capacity: '', reserved: '0 GB', warning: '', maxFileSize: '0 GB', trashRetention: '0 days', concurrentUploads: '1', allowedTypes: '', blockedExtensions: '', publicRegistration: false, allowLogin: false, maintenanceLogin: false, rememberMe: false, logoutDisabled: false, allowFolderUpload: false, allowDragDrop: false, trashEnabled: false, countTrash: false, allowRestore: false, strongPassword: false, revokeSessions: false, maintenanceEnabled: false, maintenanceMessage: '', debugUi: false, experimentalFeatures: false, minPassword: '8' }
const tabs: Array<{ id: SystemTab; label: string }> = [{ id: 'general', label: 'General' }, { id: 'access', label: 'Access' }, { id: 'storage', label: 'Storage' }, { id: 'security', label: 'Security' }, { id: 'maintenance', label: 'Maintenance' }, { id: 'advanced', label: 'Advanced' }]

// Frontend guard only: the future backend must enforce authorization for this instance-level surface.
export function SystemSettingsSection() {
  const [tab, setTab] = useState<SystemTab>('general'); const [settings, setSettings] = useState(initialSettings); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [serverSettings, setServerSettings] = useState<Record<string, unknown>>({})
  // Loading a tab synchronizes this form with the external admin settings API.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { let active = true; setLoading(true); setError(''); void systemSettingsApi.get<{ group: string; settings: Record<string, unknown> }>(tab).then(({ settings: values }) => { if (!active) return; setServerSettings(values); setSettings(current => mapServerSettings(current, values, tab)) }).catch(reason => { if (active) setError(reason instanceof Error ? reason.message : 'Unable to load system settings.') }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [tab])
  const update = <K extends keyof SystemSettings>(key: K, value: SystemSettings[K]) => setSettings(current => ({ ...current, [key]: value }))
  const toggle = (key: ToggleKey) => update(key, !settings[key])
  const canSave = ['general', 'access', 'storage', 'security', 'maintenance'].includes(tab)
  const save = async () => { const payload = mapPayload(settings, serverSettings, tab); if (!payload) return; setSaving(true); setError(''); try { const result = await systemSettingsApi.update(tab, payload); setServerSettings(result.settings); setNotice('System settings saved.'); window.setTimeout(() => setNotice(''), 2400) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save system settings.') } finally { setSaving(false) } }
  return <section className="settings-card system-settings"><div className="system-header"><div><span className="eyebrow">Administration</span><h2>System settings</h2><p>Instance-wide defaults for this private Drive deployment.</p></div><div className="system-admin-note"><ShieldCheck size={15} />Admin only</div></div><div className="system-tabs" role="tablist" aria-label="System settings sections">{tabs.map(item => <button key={item.id} role="tab" aria-selected={tab === item.id} className={tab === item.id ? 'active' : ''} onClick={() => setTab(item.id)}>{item.label}</button>)}</div>{loading ? <p role="status">Loading system settings…</p> : <>{tab === 'general' && <General settings={settings} update={update} />}{tab === 'access' && <Access settings={settings} update={update} toggle={toggle} />}{tab === 'storage' && <SystemStorage settings={settings} update={update} toggle={toggle} />}{tab === 'security' && <Security settings={settings} update={update} toggle={toggle} />}{tab === 'maintenance' && <Maintenance settings={settings} update={update} toggle={toggle} />}{tab === 'advanced' && <Advanced settings={settings} />}<div className="settings-actions"><button className="button primary" onClick={() => void save()} disabled={saving || !canSave}>{saving ? 'Saving…' : 'Save system settings'}</button></div></>}{(error || notice) && <div className={`settings-inline-notice ${error ? 'error' : ''}`} role={error ? 'alert' : 'status'}>{error || <><Check size={14} />{notice}</>}</div>}</section>
}

function mapServerSettings(current: SystemSettings, values: Record<string, unknown>, group: SystemTab): SystemSettings {
  const asGb = (value: unknown) => `${Math.round(Number(value ?? 0) / 1_000_000_000)} GB`
  if (group === 'general') return { ...current, instanceName: String(values.instanceName ?? ''), brandName: String(values.brandName ?? ''), instanceUrl: String(values.appUrl ?? ''), description: String(values.description ?? ''), language: String(values.language ?? ''), timezone: String(values.timezone ?? ''), dateFormat: String(values.dateFormat ?? ''), timeFormat: String(values.timeFormat ?? '') }
  if (group === 'access') return { ...current, publicRegistration: Boolean(values.publicRegistration), defaultRole: values.defaultRole === 'admin' ? 'Admin' : 'User' }
  if (group === 'storage') return { ...current, quota: asGb(values.defaultUserQuotaBytes), maxFileSize: asGb(values.maxUploadSizeBytes), trashRetention: `${Number(values.trashRetentionDays ?? 0)} days`, reserved: asGb(values.reservedBytes), concurrentUploads: String(values.maxConcurrentUploads ?? ''), blockedExtensions: Array.isArray(values.blockedExtensions) ? values.blockedExtensions.join(', ') : String(values.blockedExtensions ?? '') }
  if (group === 'security') return { ...current, minPassword: String(values.passwordMinLength ?? ''), strongPassword: Boolean(values.passwordRequireUppercase) && Boolean(values.passwordRequireNumber) && Boolean(values.passwordRequireSpecial) }
  if (group === 'maintenance') return { ...current, maintenanceEnabled: Boolean(values.enabled), maintenanceMessage: String(values.message ?? '') }
  if (group === 'advanced') return { ...current, debugUi: Boolean(values.debugUi), experimentalFeatures: Boolean(values.experimentalFeatures) }
  return current
}

function mapPayload(settings: SystemSettings, current: Record<string, unknown>, group: SystemTab): Record<string, unknown> | null {
  const bytes = (value: string) => Math.max(0, Number.parseFloat(value) || 0) * 1_000_000_000
  if (group === 'general') return { ...current, instanceName: settings.instanceName, brandName: settings.brandName, appUrl: settings.instanceUrl, description: settings.description, language: settings.language, timezone: settings.timezone, dateFormat: settings.dateFormat, timeFormat: settings.timeFormat }
  if (group === 'access') return { ...current, publicRegistration: settings.publicRegistration, defaultRole: settings.defaultRole.toLowerCase() }
  if (group === 'storage') return { ...current, defaultUserQuotaBytes: bytes(settings.quota), maxUploadSizeBytes: bytes(settings.maxFileSize), trashRetentionDays: Number.parseInt(settings.trashRetention, 10) || 0, reservedBytes: bytes(settings.reserved), maxConcurrentUploads: Number.parseInt(settings.concurrentUploads, 10) || 1, blockedExtensions: settings.blockedExtensions.split(',').map(value => value.trim()).filter(Boolean) }
  if (group === 'security') return { ...current, passwordMinLength: Number.parseInt(settings.minPassword, 10) || 8, passwordRequireUppercase: settings.strongPassword, passwordRequireNumber: settings.strongPassword, passwordRequireSpecial: settings.strongPassword }
  if (group === 'maintenance') return { ...current, enabled: settings.maintenanceEnabled, message: settings.maintenanceMessage }
  return null
}

function General({ settings, update }: { settings: SystemSettings; update: <K extends keyof SystemSettings>(key: K, value: SystemSettings[K]) => void }) { return <SystemGroup title="General" description="Identity and locale defaults for the instance."><div className="system-form-grid"><Field label="Instance name" value={settings.instanceName} onChange={value => update('instanceName', value)} /><Field label="Brand name" value={settings.brandName} onChange={value => update('brandName', value)} /><Field label="Instance URL" value={settings.instanceUrl} onChange={value => update('instanceUrl', value)} /><Field label="Instance description" value={settings.description} onChange={value => update('description', value)} /><SelectField label="Default language" value={settings.language} options={['English', 'Bahasa Indonesia']} onChange={value => update('language', value)} /><Field label="Timezone" value={settings.timezone} onChange={value => update('timezone', value)} /><SelectField label="Date format" value={settings.dateFormat} options={['DD/MM/YYYY', 'MM/DD/YYYY', 'YYYY-MM-DD']} onChange={value => update('dateFormat', value)} /><SelectField label="Time format" value={settings.timeFormat} options={['24-hour', '12-hour']} onChange={value => update('timeFormat', value)} /></div></SystemGroup> }
function Access({ settings, update, toggle }: { settings: SystemSettings; update: <K extends keyof SystemSettings>(key: K, value: SystemSettings[K]) => void; toggle: (key: ToggleKey) => void }) { return <SystemGroup title="Access" description="Registration and the default role for newly created accounts."><div className="system-options"><SystemToggle label="Public registration" description="Allow users to register without an invitation." checked={settings.publicRegistration} onChange={() => toggle('publicRegistration')} /><SettingField label="Default role" value={settings.defaultRole} options={['User', 'Admin']} onChange={value => update('defaultRole', value)} /></div></SystemGroup> }
function SystemStorage({ settings, update }: { settings: SystemSettings; update: <K extends keyof SystemSettings>(key: K, value: SystemSettings[K]) => void; toggle: (key: ToggleKey) => void }) { return <SystemGroup title="Storage" description="Per-user limits and upload constraints managed by the backend."><div className="system-form-grid"><Field label="Default user quota (GB)" value={settings.quota.replace(/\s*GB$/i, '')} onChange={value => update('quota', `${value} GB`)} /><Field label="Maximum upload size (GB)" value={settings.maxFileSize.replace(/\s*GB$/i, '')} onChange={value => update('maxFileSize', `${value} GB`)} /><Field label="Trash retention (days)" value={settings.trashRetention.replace(/\s*days?$/i, '')} onChange={value => update('trashRetention', `${value} days`)} /><Field label="Reserved bytes (GB)" value={settings.reserved.replace(/\s*GB$/i, '')} onChange={value => update('reserved', `${value} GB`)} /><Field label="Concurrent uploads" value={settings.concurrentUploads} onChange={value => update('concurrentUploads', value)} /><Field label="Blocked extensions" value={settings.blockedExtensions} onChange={value => update('blockedExtensions', value)} /></div></SystemGroup> }
function Security({ settings, update, toggle }: { settings: SystemSettings; update: <K extends keyof SystemSettings>(key: K, value: SystemSettings[K]) => void; toggle: (key: ToggleKey) => void }) { return <SystemGroup title="Security" description="Password requirements applied by the backend."><div className="system-options"><SystemToggle label="Require uppercase, number, and special character" description="Enforce all three password character requirements." checked={settings.strongPassword} onChange={() => toggle('strongPassword')} /><SettingField label="Minimum password length" value={settings.minPassword} options={['8', '10', '12', '16']} onChange={value => update('minPassword', value)} /></div></SystemGroup> }
function Maintenance({ settings, update, toggle }: { settings: SystemSettings; update: <K extends keyof SystemSettings>(key: K, value: SystemSettings[K]) => void; toggle: (key: ToggleKey) => void }) { return <SystemGroup title="Maintenance" description="Control maintenance mode and the message shown to users."><div className="system-options"><SystemToggle label="Maintenance mode" description="Temporarily block regular application access." checked={settings.maintenanceEnabled} onChange={() => toggle('maintenanceEnabled')} /><Field label="Maintenance message" value={settings.maintenanceMessage} onChange={value => update('maintenanceMessage', value)} /></div></SystemGroup> }
function Advanced({ settings }: { settings: SystemSettings }) { return <SystemGroup title="Advanced" description="Read-only application diagnostics and feature flags."><div className="system-options"><div className="system-toggle-row"><div><strong>Debug UI</strong><span>Configured on the server.</span></div><span>{settings.debugUi ? 'Enabled' : 'Disabled'}</span></div><div className="system-toggle-row"><div><strong>Experimental features</strong><span>Configured on the server.</span></div><span>{settings.experimentalFeatures ? 'Enabled' : 'Disabled'}</span></div></div></SystemGroup> }
function SystemGroup({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <div className="system-group"><div className="system-group-heading"><h3>{title}</h3><p>{description}</p></div>{children}</div> }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="system-field"><span>{label}</span><input className="text-input" value={value} onChange={event => onChange(event.target.value)} /></label> }
function SelectField({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label className="system-field"><span>{label}</span><select className="select-input" value={value} onChange={event => onChange(event.target.value)}>{options.map(option => <option key={option}>{option}</option>)}</select></label> }
function SettingField(props: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <SelectField {...props} /> }
function SystemToggle({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: () => void }) { return <div className="system-toggle-row"><div><strong>{label}</strong><span>{description}</span></div><button className={`toggle ${checked ? 'on' : ''}`} aria-pressed={checked} onClick={onChange}><span /></button></div> }
