'use client'

import { useEffect, useState } from 'react'
import { Check, LoaderCircle, Save, ShieldCheck } from 'lucide-react'
import { systemSettingsApi } from '@/features/admin/api/system-settings.api'

type SystemTab = 'general' | 'access' | 'storage' | 'security' | 'maintenance' | 'advanced'
type ToggleKey = 'publicRegistration' | 'allowLogin' | 'maintenanceLogin' | 'rememberMe' | 'logoutDisabled' | 'allowFolderUpload' | 'allowDragDrop' | 'trashEnabled' | 'countTrash' | 'allowRestore' | 'strongPassword' | 'revokeSessions' | 'maintenanceEnabled'
type SystemSettings = Record<ToggleKey, boolean> & { maintenanceMessage: string; instanceName: string; brandName: string; instanceUrl: string; description: string; language: string; timezone: string; dateFormat: string; timeFormat: string; userCreation: string; maxAttempts: string; sessionLifetime: string; defaultRole: string; quota: string; defaultTheme: string; defaultView: string; conflict: string; capacity: string; reserved: string; warning: string; maxFileSize: string; trashRetention: string; concurrentUploads: string; allowedTypes: string; blockedExtensions: string; minPassword: string; debugUi: boolean; experimentalFeatures: unknown[] }

const initialSettings: SystemSettings = { instanceName: '', brandName: '', instanceUrl: '', description: '', language: 'id', timezone: '', dateFormat: '', timeFormat: '', userCreation: '', maxAttempts: '', sessionLifetime: '', defaultRole: 'User', quota: '0 GB', defaultTheme: '', defaultView: '', conflict: '', capacity: '', reserved: '0 GB', warning: '', maxFileSize: '0 GB', trashRetention: '0 days', concurrentUploads: '1', allowedTypes: '', blockedExtensions: '', publicRegistration: false, allowLogin: false, maintenanceLogin: false, rememberMe: false, logoutDisabled: false, allowFolderUpload: false, allowDragDrop: false, trashEnabled: false, countTrash: false, allowRestore: false, strongPassword: false, revokeSessions: false, maintenanceEnabled: false, maintenanceMessage: '', debugUi: false, experimentalFeatures: [], minPassword: '8' }
const tabs: Array<{ id: SystemTab; label: string }> = [{ id: 'general', label: 'Umum' }, { id: 'access', label: 'Akses' }, { id: 'storage', label: 'Penyimpanan' }, { id: 'security', label: 'Keamanan' }, { id: 'maintenance', label: 'Pemeliharaan' }, { id: 'advanced', label: 'Lanjutan' }]

// Frontend guard only: the future backend must enforce authorization for this instance-level surface.
export function SystemSettingsSection() {
  const [tab, setTab] = useState<SystemTab>('general'); const [settings, setSettings] = useState(initialSettings); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [serverSettings, setServerSettings] = useState<Record<string, unknown>>({})
  // Loading a tab synchronizes this form with the external admin settings API.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { let active = true; setLoading(true); setError(''); void systemSettingsApi.get<{ group: string; settings: Record<string, unknown> }>(tab).then(({ settings: values }) => { if (!active) return; setServerSettings(values); setSettings(current => mapServerSettings(current, values, tab)) }).catch(reason => { if (active) setError(reason instanceof Error ? reason.message : 'Unable to load system settings.') }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [tab])
  const update = <K extends keyof SystemSettings>(key: K, value: SystemSettings[K]) => setSettings(current => ({ ...current, [key]: value }))
  const toggle = (key: ToggleKey) => update(key, !settings[key])
  const canSave = ['general', 'access', 'storage', 'security', 'maintenance'].includes(tab)
  const save = async () => { const payload = mapPayload(settings, serverSettings, tab); if (!payload) return; setSaving(true); setError(''); try { const result = await systemSettingsApi.update(tab, payload); setServerSettings(result.settings); setNotice('System settings saved.'); window.setTimeout(() => setNotice(''), 2400) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save system settings.') } finally { setSaving(false) } }
  return <section className="settings-card system-settings"><div className="system-header"><div><span className="eyebrow">Administrasi</span><h2>Pengaturan sistem</h2><p>Default tingkat instance untuk deployment Drive privat ini.</p></div><div className="system-admin-note"><ShieldCheck size={15} />Khusus admin</div></div><div className="system-tabs" role="tablist" aria-label="Bagian pengaturan sistem">{tabs.map(item => <button key={item.id} role="tab" aria-selected={tab === item.id} className={tab === item.id ? 'active' : ''} onClick={() => setTab(item.id)}>{item.label}</button>)}</div>{loading ? <p className="loading-state" role="status" aria-live="polite"><LoaderCircle className="spin" size={18} aria-hidden="true" /><span>Memuat pengaturan sistem…</span></p> : <>{tab === 'general' && <General settings={settings} update={update} />}{tab === 'access' && <Access settings={settings} update={update} toggle={toggle} />}{tab === 'storage' && <SystemStorage settings={settings} update={update} toggle={toggle} />}{tab === 'security' && <Security settings={settings} update={update} toggle={toggle} />}{tab === 'maintenance' && <Maintenance settings={settings} update={update} toggle={toggle} />}{tab === 'advanced' && <Advanced settings={settings} />}<div className="settings-actions"><button className="button primary" onClick={() => void save()} disabled={saving || !canSave}>{saving ? <><LoaderCircle className="spin" size={15} aria-hidden="true" /> Menyimpan…</> : <><Save size={15} aria-hidden="true" /> Simpan pengaturan sistem</>}</button></div></>}{(error || notice) && <div className={`settings-inline-notice ${error ? 'error' : ''}`} role={error ? 'alert' : 'status'}>{error || <><Check size={14} />{notice}</>}</div>}</section>
}

function mapServerSettings(current: SystemSettings, values: Record<string, unknown>, group: SystemTab): SystemSettings {
  const asGb = (value: unknown) => `${Math.round(Number(value ?? 0) / 1_000_000_000)} GB`
  if (group === 'general') return { ...current, instanceName: String(values.instanceName ?? ''), brandName: String(values.brandName ?? ''), instanceUrl: String(values.appUrl ?? ''), description: String(values.description ?? ''), language: String(values.language ?? 'id'), timezone: String(values.timezone ?? ''), dateFormat: String(values.dateFormat ?? ''), timeFormat: String(values.timeFormat ?? '') }
  if (group === 'access') return { ...current, publicRegistration: Boolean(values.publicRegistration), defaultRole: values.defaultRole === 'admin' ? 'Admin' : 'User' }
  if (group === 'storage') return { ...current, quota: asGb(values.defaultUserQuotaBytes), maxFileSize: asGb(values.maxUploadSizeBytes), trashRetention: `${Number(values.trashRetentionDays ?? 0)} days`, reserved: asGb(values.reservedBytes), concurrentUploads: String(values.maxConcurrentUploads ?? ''), blockedExtensions: Array.isArray(values.blockedExtensions) ? values.blockedExtensions.join(', ') : String(values.blockedExtensions ?? '') }
  if (group === 'security') return { ...current, minPassword: String(values.passwordMinLength ?? ''), strongPassword: Boolean(values.passwordRequireUppercase) && Boolean(values.passwordRequireNumber) && Boolean(values.passwordRequireSpecial) }
  if (group === 'maintenance') return { ...current, maintenanceEnabled: Boolean(values.enabled), maintenanceMessage: String(values.message ?? '') }
  if (group === 'advanced') return { ...current, debugUi: Boolean(values.debugUi), experimentalFeatures: Array.isArray(values.experimentalFeatures) ? values.experimentalFeatures : [] }
  return current
}

function mapPayload(settings: SystemSettings, current: Record<string, unknown>, group: SystemTab): Record<string, unknown> | null {
  const bytes = (value: string) => Math.max(0, Number.parseFloat(value) || 0) * 1_000_000_000
  if (group === 'general') return { ...current, instanceName: settings.instanceName, brandName: settings.brandName, appUrl: settings.instanceUrl, description: settings.description, language: settings.language, timezone: settings.timezone, dateFormat: settings.dateFormat, timeFormat: settings.timeFormat }
  if (group === 'access') return { ...current, publicRegistration: settings.publicRegistration, defaultRole: settings.defaultRole.toLowerCase() }
  if (group === 'storage') return { ...current, defaultUserQuotaBytes: bytes(settings.quota), maxUploadSizeBytes: bytes(settings.maxFileSize), trashRetentionDays: Number.parseInt(settings.trashRetention, 10) || 0, reservedBytes: bytes(settings.reserved), maxConcurrentUploads: Number.parseInt(settings.concurrentUploads, 10) || 1, blockedExtensions: settings.blockedExtensions.split(',').map(value => value.trim()).filter(Boolean) }
  if (group === 'security') return { ...current, passwordMinLength: Number.parseInt(settings.minPassword, 10) || 8, passwordRequireUppercase: settings.strongPassword, passwordRequireNumber: settings.strongPassword, passwordRequireSpecial: settings.strongPassword }
  if (group === 'maintenance') return { ...current, enabled: settings.maintenanceEnabled, message: settings.maintenanceMessage }
  return null
}

function General({ settings, update }: { settings: SystemSettings; update: <K extends keyof SystemSettings>(key: K, value: SystemSettings[K]) => void }) { return <SystemGroup title="Umum" description="Identitas dan default lokal untuk instance ini."><div className="system-form-grid"><Field label="Nama instance" value={settings.instanceName} onChange={value => update('instanceName', value)} /><Field label="Nama brand" value={settings.brandName} onChange={value => update('brandName', value)} /><Field label="URL instance" value={settings.instanceUrl} onChange={value => update('instanceUrl', value)} /><Field label="Deskripsi instance" value={settings.description} onChange={value => update('description', value)} /><SelectField label="Bahasa default" value={settings.language} options={[{ value: 'id', label: 'Bahasa Indonesia' }, { value: 'en', label: 'English' }]} onChange={value => update('language', value)} /><SelectField label="Zona waktu" value={settings.timezone} options={[{ value: 'Auto / Browser', label: 'Auto / Browser' }, { value: 'Asia/Jakarta', label: 'Asia/Jakarta — WIB' }, { value: 'Asia/Makassar', label: 'Asia/Makassar — WITA' }, { value: 'Asia/Jayapura', label: 'Asia/Jayapura — WIT' }, { value: 'UTC', label: 'UTC' }]} onChange={value => update('timezone', value)} /><SelectField label="Format tanggal" value={settings.dateFormat} options={['DD/MM/YYYY', 'MM/DD/YYYY', 'YYYY-MM-DD']} onChange={value => update('dateFormat', value)} /><SelectField label="Format waktu" value={settings.timeFormat} options={[{ value: '24-hour', label: '24 jam' }, { value: '12-hour', label: '12 jam' }]} onChange={value => update('timeFormat', value)} /></div></SystemGroup> }
function Access({ settings, update, toggle }: { settings: SystemSettings; update: <K extends keyof SystemSettings>(key: K, value: SystemSettings[K]) => void; toggle: (key: ToggleKey) => void }) { return <SystemGroup title="Akses" description="Pendaftaran dan peran default untuk akun baru."><div className="system-options"><SystemToggle label="Pendaftaran publik" description="Izinkan pengguna mendaftar tanpa undangan." checked={settings.publicRegistration} onChange={() => toggle('publicRegistration')} /><SettingField label="Peran default" value={settings.defaultRole} options={['User', 'Admin']} onChange={value => update('defaultRole', value)} /></div></SystemGroup> }
function SystemStorage({ settings, update }: { settings: SystemSettings; update: <K extends keyof SystemSettings>(key: K, value: SystemSettings[K]) => void; toggle: (key: ToggleKey) => void }) { return <SystemGroup title="Penyimpanan" description="Batas per pengguna dan aturan unggahan yang dikelola backend."><div className="system-form-grid"><Field label="Kuota pengguna default (GB)" value={settings.quota.replace(/\s*GB$/i, '')} onChange={value => update('quota', `${value} GB`)} /><Field label="Ukuran unggahan maksimum (GB)" value={settings.maxFileSize.replace(/\s*GB$/i, '')} onChange={value => update('maxFileSize', `${value} GB`)} /><Field label="Retensi sampah (hari)" value={settings.trashRetention.replace(/\s*days?$/i, '')} onChange={value => update('trashRetention', `${value} days`)} /><Field label="Byte cadangan (GB)" value={settings.reserved.replace(/\s*GB$/i, '')} onChange={value => update('reserved', `${value} GB`)} /><Field label="Unggahan bersamaan" value={settings.concurrentUploads} onChange={value => update('concurrentUploads', value)} /><Field label="Ekstensi yang diblokir" value={settings.blockedExtensions} onChange={value => update('blockedExtensions', value)} /></div></SystemGroup> }
function Security({ settings, update, toggle }: { settings: SystemSettings; update: <K extends keyof SystemSettings>(key: K, value: SystemSettings[K]) => void; toggle: (key: ToggleKey) => void }) { return <SystemGroup title="Keamanan" description="Persyaratan kata sandi yang diterapkan backend."><div className="system-options"><SystemToggle label="Wajib huruf besar, angka, dan karakter khusus" description="Terapkan ketiga persyaratan karakter kata sandi." checked={settings.strongPassword} onChange={() => toggle('strongPassword')} /><SettingField label="Panjang kata sandi minimum" value={settings.minPassword} options={['8', '10', '12', '16']} onChange={value => update('minPassword', value)} /></div></SystemGroup> }
function Maintenance({ settings, update, toggle }: { settings: SystemSettings; update: <K extends keyof SystemSettings>(key: K, value: SystemSettings[K]) => void; toggle: (key: ToggleKey) => void }) { return <SystemGroup title="Pemeliharaan" description="Atur mode pemeliharaan dan pesan yang dilihat pengguna."><div className="system-options maintenance-settings"><SystemToggle label="Mode pemeliharaan" description="Saat aktif, pengguna biasa tidak dapat menggunakan Drive. Administrator tetap dapat mengakses halaman administrasi." checked={settings.maintenanceEnabled} onChange={() => toggle('maintenanceEnabled')} /><TextAreaField label="Pesan pemeliharaan" value={settings.maintenanceMessage} onChange={value => update('maintenanceMessage', value)} /></div></SystemGroup> }
function Advanced({ settings }: { settings: SystemSettings }) { const flagCount = settings.experimentalFeatures.length; return <SystemGroup title="Lanjutan" description="Informasi runtime yang aman dan hanya-baca."><div className="system-options"><div className="system-toggle-row"><div><strong>Debug UI</strong><span>Dikonfigurasi di server. Hanya-baca.</span></div><span className="system-readonly-value">{settings.debugUi ? 'Aktif' : 'Nonaktif'}</span></div><div className="system-toggle-row"><div><strong>Fitur eksperimental</strong><span>{flagCount > 0 ? 'Flag terdaftar di server; tidak dapat diubah dari UI.' : 'Tidak ada feature flag terdaftar di server.'}</span></div><span className="system-readonly-value">{flagCount > 0 ? `${flagCount} flag terdaftar` : 'Tidak dikonfigurasi'}</span></div></div></SystemGroup> }
function SystemGroup({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <div className="system-group"><div className="system-group-heading"><h3>{title}</h3><p>{description}</p></div>{children}</div> }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="system-field"><span>{label}</span><input className="text-input" value={value} onChange={event => onChange(event.target.value)} /></label> }
function TextAreaField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="system-field"><span>{label}</span><textarea className="text-input" value={value} rows={4} onChange={event => onChange(event.target.value)} /></label> }
type SelectOption = string | { value: string; label: string }
function SelectField({ label, value, options, onChange }: { label: string; value: string; options: SelectOption[]; onChange: (value: string) => void }) { return <label className="system-field"><span>{label}</span><select className="select-input" value={value} onChange={event => onChange(event.target.value)}>{options.map(option => { const item = typeof option === 'string' ? { value: option, label: option } : option; return <option key={item.value} value={item.value}>{item.label}</option> })}</select></label> }
function SettingField(props: { label: string; value: string; options: SelectOption[]; onChange: (value: string) => void }) { return <SelectField {...props} /> }
function SystemToggle({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: () => void }) { return <div className="system-toggle-row"><div><strong>{label}</strong><span>{description}</span></div><button className={`toggle ${checked ? 'on' : ''}`} aria-pressed={checked} onClick={onChange}><span /></button></div> }
