'use client'

import { useEffect, useMemo, useState } from 'react'
import { Copy, Mail, MoreHorizontal, Search, ShieldCheck, UserPlus, UserX } from 'lucide-react'
import { Modal } from '@/components/ui/Modal'
import { buildInvitationUrl, buildVerificationUrl } from '@/lib/user-links'
import { formatBytes, formatDate, percentageOf } from '@/lib/format'
import { usersApi as userService } from '@/features/admin/api/users.api'
import type { AccountSetupMethod } from '@/features/admin/types/user.types'
import { useUserStore } from '@/stores/user-store'
import type { CloudUser, UserRole, UserStatus } from '@/types/user'

const statusLabel: Record<UserStatus, string> = { pending: 'Pending', active: 'Active', disabled: 'Disabled' }

export function UserManagement({ showNotice }: { showNotice: (message: string) => void }) {
  const store = useUserStore()
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState<'all' | UserStatus>('all')
  const [role, setRole] = useState<'all' | UserRole>('all')
  const [addOpen, setAddOpen] = useState(false)
  const [selected, setSelected] = useState<CloudUser | null>(null)
  const activeAdmins = store.users.filter(user => user.role === 'admin' && user.status === 'active').length
  const filtered = useMemo(() => store.users.filter(user => {
    const haystack = `${user.name} ${user.email}`.toLowerCase()
    return haystack.includes(query.toLowerCase()) && (status === 'all' || user.status === status) && (role === 'all' || user.role === role)
  }), [query, role, status, store.users])
  const allocated = store.users.reduce((sum, user) => sum + user.quotaBytes, 0)
  const pending = store.users.filter(user => user.status === 'pending').length
  const canDelete = (user: CloudUser) => user.id !== store.currentUserId && !(user.role === 'admin' && activeAdmins <= 1)

  return <section className="settings-card user-management"><div className="settings-section-header"><div><span className="eyebrow">Administration</span><h2>User management</h2><p>Invite people, manage access, and keep workspace allocation visible.</p></div><button className="button primary" onClick={() => setAddOpen(true)}><UserPlus size={15} /> Add user</button></div>
    <div className="user-metrics"><Metric label="Total users" value={String(store.users.length)} /><Metric label="Active" value={String(store.users.filter(user => user.status === 'active').length)} /><Metric label="Pending invitations" value={String(pending)} /><Metric label="Storage allocation" value={formatBytes(allocated)} /></div>
    <div className="user-management-toolbar"><label className="user-search"><Search size={15} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search name or email" aria-label="Search users" /></label><select className="select-input" value={role} onChange={event => setRole(event.target.value as 'all' | UserRole)}><option value="all">All roles</option><option value="admin">Admins</option><option value="user">Users</option></select><select className="select-input" value={status} onChange={event => setStatus(event.target.value as 'all' | UserStatus)}><option value="all">All status</option><option value="active">Active</option><option value="pending">Pending</option><option value="disabled">Disabled</option></select></div>
    <div className="user-table-wrap"><table className="user-table"><thead><tr><th>Person</th><th>Role</th><th>Status</th><th>Email verification</th><th>Storage</th><th>Last active</th><th aria-label="Actions" /></tr></thead><tbody>{filtered.map(user => <UserRow key={user.id} user={user} onOpen={() => setSelected(user)} />)}</tbody></table><div className="user-mobile-list">{filtered.map(user => <UserMobileCard key={user.id} user={user} onOpen={() => setSelected(user)} />)}</div>{filtered.length === 0 && <p className="empty-state">No users match these filters.</p>}</div>
    {addOpen && <AddUserDialog onClose={() => setAddOpen(false)} onCreated={user => { setAddOpen(false); setSelected(user); showNotice(user.status === 'pending' ? 'Invitation created' : 'User created') }} />}
    {selected && <UserDetails user={selected} currentUserId={store.currentUserId} adminCount={activeAdmins} canDelete={canDelete(selected)} onClose={() => setSelected(null)} onNotice={showNotice} onRefresh={next => setSelected(next)} />}
  </section>
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="user-metric"><span>{label}</span><strong>{value}</strong></div> }
function UserRow({ user, onOpen }: { user: CloudUser; onOpen: () => void }) { const used = percentageOf(user.usedBytes, user.quotaBytes); return <tr><td><button className="user-person user-link" onClick={onOpen}><span className="avatar">{user.initials}</span><span><strong>{user.name}</strong><small>{user.email}</small></span></button></td><td>{user.role === 'admin' ? 'Admin' : 'User'}</td><td><span className={`status-pill ${user.status}`}>{statusLabel[user.status]}</span></td><td><span className={`verification-label ${user.emailVerifiedAt ? 'verified' : ''}`}>{user.emailVerifiedAt ? 'Verified' : 'Not verified'}</span></td><td><span className="user-storage-line">{formatBytes(user.usedBytes)} / {formatBytes(user.quotaBytes)}</span><i className="user-meter"><em style={{ width: `${Math.min(used, 100)}%` }} /></i></td><td>{user.lastActiveAt ? formatDate(user.lastActiveAt) : '—'}</td><td><button className="icon-button" onClick={onOpen} aria-label={`Manage ${user.name}`}><MoreHorizontal size={16} /></button></td></tr> }
function UserMobileCard({ user, onOpen }: { user: CloudUser; onOpen: () => void }) { const used = percentageOf(user.usedBytes, user.quotaBytes); return <article className="user-mobile-card"><button className="user-person user-link" onClick={onOpen}><span className="avatar">{user.initials}</span><span><strong>{user.name}</strong><small>{user.email}</small></span></button><div className="user-mobile-meta"><span className={`status-pill ${user.status}`}>{statusLabel[user.status]}</span><span>{user.role === 'admin' ? 'Admin' : 'User'}</span><span className={user.emailVerifiedAt ? 'verification-label verified' : 'verification-label'}>{user.emailVerifiedAt ? 'Verified' : 'Not verified'}</span></div><div className="user-mobile-storage"><span>{formatBytes(user.usedBytes)} / {formatBytes(user.quotaBytes)}</span><i className="user-meter"><em style={{ width: `${Math.min(used, 100)}%` }} /></i></div><button className="button secondary" onClick={onOpen}>Manage</button></article> }

function AddUserDialog({ onClose, onCreated }: { onClose: () => void; onCreated: (user: CloudUser) => void }) {
  const store = useUserStore(); const [setup, setSetup] = useState<AccountSetupMethod>('invitation'); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [role, setRole] = useState<UserRole>('user'); const [quota, setQuota] = useState('25'); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [policy, setPolicy] = useState<{ minimumPasswordLength: number; requireUppercase: boolean; requireNumber: boolean; requireSpecialCharacter: boolean } | null>(null)
  useEffect(() => { userService.getPasswordPolicy().then(setPolicy).catch(reason => setError(reason instanceof Error ? reason.message : 'Unable to load password policy.')) }, [])
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!name.trim() || !email.trim()) { setError('Name and email are required.'); return } if (setup === 'manual' && (!policy || password.length < policy.minimumPasswordLength || policy.requireUppercase && !/[A-Z]/.test(password) || policy.requireNumber && !/\d/.test(password) || policy.requireSpecialCharacter && !/[^A-Za-z0-9]/.test(password) || password !== confirm)) { setError(policy ? `Password must meet the configured policy and match confirmation.` : 'Password policy is still loading.'); return } try { const user = await store.addUser({ name: name.trim(), email: email.trim(), role, quotaBytes: Math.max(Number(quota), 1) * 1_000_000_000, setup, password }); onCreated(user) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to create user.') } }
  return <Modal title="Add user" onClose={onClose}><form className="settings-form" onSubmit={submit}><div className="setup-methods"><label className={setup === 'invitation' ? 'selected' : ''}><input type="radio" checked={setup === 'invitation'} onChange={() => setSetup('invitation')} /> <Mail size={16} /><span><strong>Send invitation</strong><small>User sets their password from a secure link.</small></span></label><label className={setup === 'manual' ? 'selected' : ''}><input type="radio" checked={setup === 'manual'} onChange={() => setSetup('manual')} /> <ShieldCheck size={16} /><span><strong>Admin sets password</strong><small>Account is active immediately.</small></span></label></div><div className="user-form-grid"><label>Name<input className="text-input" value={name} onChange={event => setName(event.target.value)} autoComplete="name" /></label><label>Email<input className="text-input" type="email" value={email} onChange={event => setEmail(event.target.value)} autoComplete="email" /></label><label>Role<select className="select-input" value={role} onChange={event => setRole(event.target.value as UserRole)}><option value="user">User</option><option value="admin">Admin</option></select></label><label>Quota (GB)<input className="text-input" type="number" min="1" value={quota} onChange={event => setQuota(event.target.value)} /></label></div>{setup === 'manual' && <div className="password-fields"><label>Initial password<input className="text-input" type="password" value={password} onChange={event => setPassword(event.target.value)} autoComplete="new-password" /></label><label>Confirm password<input className="text-input" type="password" value={confirm} onChange={event => setConfirm(event.target.value)} autoComplete="new-password" /></label></div>}{error && <p className="form-hint error">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary">{setup === 'invitation' ? 'Create invitation' : 'Create user'}</button></div></form></Modal>
}

function UserDetails({ user, currentUserId, adminCount, canDelete, onClose, onNotice, onRefresh }: { user: CloudUser; currentUserId: string; adminCount: number; canDelete: boolean; onClose: () => void; onNotice: (message: string) => void; onRefresh: (user: CloudUser) => void }) {
  const store = useUserStore(); const [editing, setEditing] = useState(false); const [name, setName] = useState(user.name); const [quota, setQuota] = useState(String(Math.round(user.quotaBytes / 1_000_000_000))); const [role, setRole] = useState(user.role)
  const save = async (event: React.FormEvent) => { event.preventDefault(); const nextQuota = Number(quota) * 1_000_000_000; if (nextQuota < user.usedBytes) { onNotice('Quota cannot be below current usage'); return } try { const updated = await store.updateUser(user.id, { name, role, quotaBytes: nextQuota }); onRefresh(updated); setEditing(false); onNotice('User updated') } catch (error) { onNotice(error instanceof Error ? error.message : 'Unable to update user.') } }
  const action = async (status: UserStatus) => { if (status === 'disabled' && user.id === currentUserId) { onNotice('You cannot disable your own account'); return } try { const updated = await store.setStatus(user.id, status); onRefresh(updated); onNotice(status === 'disabled' ? 'User disabled' : 'User enabled') } catch (error) { onNotice(error instanceof Error ? error.message : 'Unable to update user status.') } }
  const link = user.invitationToken ? buildInvitationUrl(user.invitationToken) : user.verificationToken ? buildVerificationUrl(user.verificationToken) : ''
  return <Modal title={`Manage ${user.name}`} onClose={onClose}>{editing ? <form className="settings-form" onSubmit={save}><label>Name<input className="text-input" value={name} onChange={event => setName(event.target.value)} /></label><label>Email<input className="text-input" value={user.email} readOnly /></label><label>Role<select className="select-input" disabled={user.id === currentUserId || (user.role === 'admin' && adminCount <= 1)} value={role} onChange={event => setRole(event.target.value as UserRole)}><option value="user">User</option><option value="admin">Admin</option></select></label><label>Quota (GB)<input className="text-input" type="number" min="1" value={quota} onChange={event => setQuota(event.target.value)} /></label><div className="modal-actions"><button type="button" className="button secondary" onClick={() => setEditing(false)}>Cancel</button><button className="button primary">Save changes</button></div></form> : <><div className="user-detail-heading"><span className="avatar">{user.initials}</span><div><strong>{user.name}</strong><span>{user.email}</span></div></div><dl className="details-grid"><dt>Role</dt><dd>{user.role === 'admin' ? 'Administrator' : 'User'}</dd><dt>Status</dt><dd>{statusLabel[user.status]}</dd><dt>Verification</dt><dd>{user.emailVerifiedAt ? `Verified ${formatDate(user.emailVerifiedAt)}` : 'Not verified'}</dd><dt>Storage</dt><dd>{formatBytes(user.usedBytes)} of {formatBytes(user.quotaBytes)}</dd><dt>Created</dt><dd>{formatDate(user.createdAt)}</dd></dl>{link && <div className="user-detail-link"><input className="text-input" value={link} readOnly /><button className="button secondary" onClick={() => void navigator.clipboard?.writeText(link).then(() => onNotice('Link copied'))}><Copy size={14} /> Copy</button></div>}<div className="modal-actions"><button className="button secondary" onClick={() => setEditing(true)}>Edit user</button>{user.status === 'active' ? <button className="button secondary" disabled={user.id === currentUserId} onClick={() => action('disabled')}><UserX size={14} /> Disable</button> : user.status === 'disabled' ? <button className="button secondary" onClick={() => action('active')}>Enable</button> : <button className="button secondary" onClick={async () => { try { await store.resendInvitation(user.id); onNotice('Invitation resent') } catch (error) { onNotice(error instanceof Error ? error.message : 'Unable to resend invitation.') } }}>Resend invitation</button>}{canDelete && <button className="button secondary destructive" onClick={async () => { try { await store.deleteUser(user.id); onClose(); onNotice('User deleted') } catch (error) { onNotice(error instanceof Error ? error.message : 'Unable to delete user.') } }}>Delete</button>}</div></>}</Modal>
}
